.circleci/config.yml

We can release 0.1.0 from github after that.

fix: release process for circleci

---

packages/graphback-cli/src/templates/modelTemplates.ts
packages/graphback-cli/src/templates/starterTemplates.ts
packages/graphback-cli/src/templates/templateMetadata.ts
packages/graphback-cli/src/utils/initHelper.ts
packages/graphback/src/resolvers/ResolverGenerator.ts

During `graphback init` ask if user want's to include model or not. If yes, include one of the example models, if not create a file with commented out text
Fix indentation in template literals(new line strings)

feat: ask for model in init workflow

---

packages/graphback/src/resolvers/ResolverBuilder.ts
packages/graphback/src/resolvers/ResolverManager.ts
packages/graphback/src/resolvers/ResolverType.ts
packages/graphback/src/schema/partials/interface.handlebars
packages/graphback/src/schema/partials/query.handlebars

```
type Note {
id: ID!
title: String!
description: String!
}
```
```
interface Node {
id: ID!
}
input NoteFilter {
id: ID
title: String
description: String
}
type PaginationInfo {
totalPages: Int!
totalItems: Int!
page: Int!
perPage: Int!
hasNextPage: Boolean!
hasPreviousPage: Boolean!
}
type Note implements Node  {
id: ID!
title: String!
description: String!
}
input NoteInput {
title: String
description: String
}
type NotePagination {
items: [Note]!
pageInfo: PaginationInfo!
}
type Query {
findNote(fields: NoteFilter): Note!
findAllNotes: NotePagination
}
type Mutation {
createNote(input: NoteInput!): Note!
updateNote(id: ID!, input: NoteInput!): Note!
deleteNote(id: ID!): ID!
}
type Subscription {
newNote: Note!
updatedNote: Note!
deletedNote: ID!
}
```
#60

Make schema using opiniated pattersn

---

packages/graphback/src/resolvers/knex/resolverImplementation.ts
packages/graphback/src/resolvers/knex/targetResolverContext.ts
packages/graphback/src/resolvers/resolverTemplate.ts
packages/graphback/src/schema/targetSchemaContext.ts
templates/apollo-starter-ts/generated/resolvers.ts
templates/apollo-starter-ts/generated/schema.ts
templates/apollo-starter-ts/src/config/config.ts
templates/apollo-starter-ts/src/mapping.ts

Checked working of graphback by going through the flow of commands
Fixed:
- resolver implementation of create, update
- schema def of find method
- template mapping

fix: change resolver implementation, edit template mapping

---

packages/graphback/src/resolvers/knex/resolverImplementation.ts
packages/graphback/src/resolvers/resolverTemplate.ts
templates/apollo-starter-ts/.gitignore
templates/apollo-starter-ts/generated/resolvers.ts
templates/apollo-starter-ts/package.json
templates/apollo-starter-ts/src/config/config.ts
templates/apollo-starter-ts/src/context.ts
templates/apollo-starter-ts/src/db.ts
templates/apollo-starter-ts/src/index.ts
templates/apollo-starter-ts/tsconfig.json
templates/apollo-starter-ts/tslint.json

Fix for #122
- add tsconfig.json, build script and configuration
- Fix typescript compile errors
- Create Context interface for resolver context
```
export interface Context {
pubsub: RedisPubSub
req: express.Request
db: knex<any, unknown[]>
}
```
- Typings in resolvers
```
key: (_: any, args: any, context: Context) => { }
```

fix: make apollo-template compile in typescript

---

packages/graphback-cli/src/templates/resources/config/pgconfig.json
packages/graphback-cli/src/templates/resources/docker/pg-docker-compose.yml
templates/apollo-starter-ts/package.json
templates/apollo-starter-ts/src/config/config.ts
templates/apollo-starter-ts/src/subscriptions.ts

- Change postgres port mapping from `5432` to `55432`
- Change redis port mapping from `6379` to `6789`

fix: ports for postgres and redis, add redis config

---

templates/apollo-rest-starter/package.json
templates/apollo-rest-starter/src/config/config.ts
templates/apollo-rest-starter/src/index.ts
templates/apollo-starter-ts/package.json
templates/apollo-starter-ts/src/config/config.ts
templates/apollo-starter-ts/src/index.ts

fix: change playground from altair to graphql-playground

---

packages/graphback-cli/src/templates/resources/models/Tasks.graphql

Added `createdWhen: TimeDetails` and replaced enum with String.

Modified Tasks.graphql

---

website/siteConfig.js

Tagline did not clearly explain the purpose of the project

chore: Change tagline

---

README.md

Hey guys, the readme is great but I just wanted to create a small PR to give it some polish.
Hoping to make some more meaningful contributions over the coming weeks. The library is great!

fix: grammar in readme

---

docs/config.md
packages/graphback-cli/src/templates/configTemplates.ts
packages/graphback/example/index.ts
packages/graphback/src/ContextTypes.ts
packages/graphback/src/InputTypeVisitor.ts
packages/graphback/src/directives.ts
packages/graphback/src/resolvers/knex/targetResolverContext.ts
packages/graphback/src/schema/targetSchemaContext.ts
packages/graphback/tests/empty-test.ts

This is literally my very first attempt at contributing to open source so please be gentle. :-)
Sorry for the changes reflected in removing trailing spaces. Must be an editor configuration. I didn't do that intentionally.
I did my best to follow the contribution guidelines and everything seemed to run just fine.
I spent an hour or more reasoning through the ticket and walking through code. I **think** I did the right thing.
I tried to break tests by setting `"disableGen": true` in `empty-test.js` but couldn't get the tests to fail so I probably need a nudge in the right direction to update tests.
If `@disableGen` is looking right then I'll try and replicate it for `@rest`.

Adds and uses disableGen Type directive

---

docs/config.md
packages/graphback/src/InputTypeVisitor.ts
packages/graphback/src/resolvers/knex/targetResolverContext.ts
packages/graphback/src/resolvers/outputResolvers/resolverTemplate.ts
packages/graphback/src/schema/schemaTemplate.ts
packages/graphback/src/schema/targetSchemaContext.ts

- restructure schema and resolver templates to not leave empty spaces
- enforce disableGen  for all operations
- add info about disableGen in docs

fix: reformat string templates, disableGen usage

---

docs/releases.md
docs/templates.md
packages/graphback-cli/src/commands/init.ts
packages/graphback-cli/src/helpers/init.ts

Add ability to use separate templates from github repositories. 
I'm not sure how to provide custom path so provided fixed template
```
graphback init test ---templateUrl=https://github.com/aerogear/modern-appdev-workshop#
```

Templateurl support

---

packages/graphback/src/datasource/DataResourcesManager.ts
packages/graphback/src/resolvers/knex/BaseKnexResolver.ts
packages/graphback/src/resolvers/knex/targetResolverContext.ts
packages/graphback/src/schema/targetSchemaContext.ts

This PR tweaks one-to-one relationships to work as described in issue #209. It touches database, schema, and resolvers.

Tweak one-to-one relationships

---

docs/gettingstarted.md
templates/apollo-rest-starter/package.json
templates/apollo-starter-ts/package.json
templates/graphql-js-starter/package.json

- Change `start` to script use compiled code.
- remove `watch` command from package.json
- add `develop` script for ts-node
#240 #216

change start script and update docs

---

packages/graphback-cli/src/helpers/init.ts
packages/graphback-cli/src/templates/configTemplates.ts
packages/graphback-cli/src/templates/resources/docker/sqlite3.yml
packages/graphback-cli/src/templates/resources/subscriptions.ts
templates/apollo-rest-starter/src/context.ts
templates/apollo-starter-ts/src/context.ts
templates/graphql-js-starter/src/context.ts

Remove dependency of docker-compose in case of `sqlite3` database.

In memory subscriptions for sqlite3

---

lerna.json
packages/graphback-cli/package.json
packages/graphback-cli/src/templates/configTemplates.ts
packages/graphback-cli/src/templates/resources/subscriptions.ts
packages/graphback/package.json
templates/apollo-rest-starter/package.json
templates/apollo-starter-ts/package.json
templates/graphql-js-starter/package.json

Reverting breaking changes. We need to think how to do this properly.

fix: issue with missing files in templates cli

---

website/blog/2019-08-27-crash-course-on-graphback.md

New blog was breaking, due to date problem in filename

Fix blog in documentation

---

packages/graphback-cli/src/helpers/index.ts
packages/graphback-cli/src/index.ts
packages/graphql-cli-graphback-plugin/README.md
packages/graphql-cli-graphback-plugin/package.json
packages/graphql-cli-graphback-plugin/src/commands/backend-db.ts
packages/graphql-cli-graphback-plugin/src/commands/backend-generate.ts
packages/graphql-cli-graphback-plugin/src/commands/backend-init.ts
packages/graphql-cli-graphback-plugin/src/index.ts
packages/graphql-cli-graphback-plugin/tsconfig.json

#289 
```sh
npm install
```
```sh
npm run bootstrap
```
```sh
npm run build
```
```sh
graphql
```
Should produce GraphQL-CLI options along with Graphback options.

feat: GraphQL CLI plugin for graphback

---

.vscode/launch.json
CONTRIBUTING.md

Add more info how to use CLI and debug configuration

chore: Simplify contribution guide

---

docs/databases.md
lerna.json
packages/graphback-cli/package.json
packages/graphback-cli/src/config/ConfigBuilder.ts
packages/graphback/package.json
packages/graphback/src/datasource/DataResourcesManager.ts
packages/graphql-cli-graphback-plugin/package.json
templates/apollo-starter-ts/package.json

1. Add model to ts-template
2. Execute db in debug mode.

fix: fix graphback db command

---

packages/graphback-cli/src/index.ts

add shorthand CLI flag for `--help`

---

README.md

Just adding badge for issue #382 =)

Add Discord (chat) badge to README

---

packages/graphback/src/generators/client/targetContext.ts

This Pull Request corrects the implementation of methods that generates client queries and mutations, adding the symbol $ where it was missing.
Fixes #401

fix: VariableFields and inputVariableFields methods

---

lerna.json
packages/graphback-cli/package.json
packages/graphback/package.json
packages/graphql-cli-graphback-plugin/package.json
templates/apollo-runtime-ts/package.json
templates/apollo-starter-ts/package.json

fix: Prerelease runtime components

---

templates/apollo-starter-ts/migrations/Previous.graphql
templates/apollo-starter-ts/model/User.graphql
templates/apollo-starter-ts/src/schema/generated.ts

- `generated.ts` was deleted by accident.
- Schema files should not be included in template.

[FIX] Add default generated file back in

---

docs/templates.md

Edit: link

---

packages/graphback/README.md

Removed line: GraphQL can be hard and intimidating initially.

Fix: Remove meaningless line

---

packages/graphback-cli/package.json
packages/graphback-codegen-client/package.json
packages/graphback-codegen-resolvers/package.json
packages/graphback-codegen-schema/package.json
packages/graphback-core/package.json
packages/graphback-db-manage/package.json
packages/graphback-runtime/package.json
packages/graphback/package.json

No verification needed. Going to be verified by renovate

fix: Use valid engines for renovate

---

packages/graphback-cli/package.json
packages/graphback-cli/src/helpers/init.ts
packages/graphback-cli/src/templates/modelTemplates.ts
packages/graphback-cli/src/templates/starterTemplates.ts

Ora do not support typings anymore.
It introduces problems in tests and ci logs for little value to user.

fix: remove ora

---

examples/generator-fullstack/tsconfig.json
examples/runtime-example/package.json
examples/runtime-example/tsconfig.json
packages/graphback-cli/tsconfig.json
packages/graphback-codegen-client/package.json
packages/graphback-codegen-resolvers/package.json
packages/graphback-codegen-schema/package.json
packages/graphback-core/package.json
packages/graphback-db-manage/package.json
packages/graphback-db-manage/tsconfig.json
packages/graphback-runtime/package.json
packages/graphback-runtime/tsconfig.json
packages/graphback/package.json
packages/graphback/tsconfig.json

Removing invalid typings and not needed packages. Added extra typescript flag to support latest promise

chore: cleanup package and build process

---

packages/graphback-codegen-resolvers/src/api/ResolverGeneratorOptions.ts
packages/graphback-codegen-resolvers/src/api/createResolvers.ts
packages/graphback-codegen-resolvers/src/api/resolverTypes.ts
packages/graphback-codegen-resolvers/src/index.ts
packages/graphback-codegen-resolvers/tests/ApolloServiceResolverGeneratorTest.ts
packages/graphback-codegen-schema/src/createSchema.ts
packages/graphback-codegen-schema/src/index.ts
packages/graphback/src/GraphQLBackendCreator.ts

Changes tested in graphql-cli already. Mostly renaming to have unified patter for generators and also adding missing types
https://github.com/aerogear/graphback/issues/506

Api improvements

---

examples/generator-fullstack/model/datamodel.graphql
packages/graphback-codegen-client/src/templates/gqlTemplates.ts

Revert changes to `createMutations`

---

integration/tests/basic-runtime.ts
packages/graphback-codegen-resolvers/src/templates/LayeredResolverTemplates.ts
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverGen.ts

Implementing missing one-to-many relation in runtime package

chore: add one-to-many resolver to runtime package

---

docs/database-schema-migrations.md

Fixes https://github.com/aerogear/graphback/issues/554

docs: Documentation for the custom field names

---

docs/database-schema-migrations.md
docs/datamodel.md

See https://github.com/aerogear/graphback/issues/551

fix: documentation for the fixed ID field

---

packages/graphback-cli/src/index.ts

feat(cli): recommend matching commands

---

README.md

Made the license badge lead to the respective file.

fix(docs): update reference

---

docs/releases.md

Closes https://github.com/aerogear/graphback/issues/584

Add database migrations to release notes for 0.10.0

---

docs/clientsidequeries.md
docs/commands.md
docs/gettingstarted.md
docs/releases.md

Apply some fixes to documentation

Fixes to documentation

---

.vscode/launch.json
packages/graphback-cli/src/templates/modelTemplates.ts

fix: Use relative path for models

---

packages/graphback-codegen-client/src/templates/gqlCompleteTemplates.ts
packages/graphback-codegen-client/src/templates/gqlTemplates.ts
packages/graphback-codegen-client/src/templates/tsTemplates.ts
packages/graphback-codegen-resolvers/src/output/createResolvers.ts
packages/graphback-codegen-schema/src/plugin/SchemaCRUDPlugin.ts
packages/graphback-core/package.json
packages/graphback-core/src/crud/GraphbackOperationType.ts
packages/graphback-core/src/crud/mappingHelpers.ts
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverGen.ts

Do preliminary work to control all mappings and split between static CRUD mappings and CRUD layer mappins like id/tablename etc.

fix: Mapping refactor

---

.gitignore
package.json

@wtrocki Only 3 lines added in package.json.

resolutions added in package.json

---

packages/graphback-runtime-mongodb/createMongoDbRuntimeContext.ts
packages/graphback-runtime-mongodb/src/OffixMongoDBDataProvider.ts

Required changes tested with showcase

fix: Add version updates on create for offix implementation

---

packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts

Mongodb batching

---

packages/graphback-runtime-mongodb/src/OffixMongoDBDataProvider.ts

Add Versioning changes to offix. When updating we need to bump version.
There is still bug about updates. I think offix need to have by definition an soft updates so we can introduce `_deleted` field

fix: Offix version bump

---

docs/crud/relationships.md
docs/db/migrations.md

Add website documentation on how to map relationships in CRUD and migrations.

docs: relationship mapping

---

docs/intro/existingproject.md
packages/graphback-cli/src/components/config.ts
packages/graphback-cli/src/templates/configTemplates.ts
packages/graphback-cli/src/templates/modelTemplates.ts

Small improvements to CLI config command

---

integration/tests/codegen-workflow.ts
packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
packages/graphback-runtime/src/GraphbackPage.ts
packages/graphback-runtime/src/data/GraphbackDataProvider.ts
packages/graphback-runtime/src/data/RESTDataProvider.ts
packages/graphback-runtime/src/index.ts
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts
packages/graphback-runtime/src/service/CRUDService.ts
packages/graphback-runtime/src/service/GraphbackCRUDService.ts

This PR does the following:
- Update CRUD services to use pagination in findall
- Update Runtime Resolver Creator to use pagination in findall
Relevant issue: #867

Fix findall pagination

---

package.json
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/OffixMongoDBDataProvider.ts

Fixes https://github.com/aerogear/graphback/issues/1117
This adds a check for a missing ID value from the mutation and throws an appropriate error.

Add check for undefined ID in MongoDb update and delete

---

packages/graphback-core/src/annotations/parser.ts
packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts
packages/graphback-core/tests/EngineTests.ts
packages/graphback-core/tests/MetadataTest.ts
packages/graphback-core/tests/__snapshots__/EngineTests.ts.snap
packages/graphback-core/tests/__snapshots__/MetadataTest.ts.snap
packages/graphback-core/tests/mock.graphql

Using Object.assign without understanding how it works :)
See https://github.com/aerogear/graphback/issues/1120

fix: Problem with CRUD config being global

---

packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts

Verification possible in AtHomeCrisisCommunity

fix: Mongo batching with string as key

---

packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts

Improved version that does only single loop

fix: Mongo batching for types

---

packages/graphback-codegen-offix/package.json
packages/graphback-codegen-schema/package.json
packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts
packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
packages/graphback-codegen-schema/tests/mock.graphql
packages/graphback-core/package.json
packages/graphback-core/src/index.ts
packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts
packages/graphback-core/src/plugin/getModelTypesFromSchema.ts
packages/graphback-core/src/utils/printSchemaWithDirectives.ts
packages/graphback-core/tests/RelationshipMetadataBuilderTest.ts
packages/graphback-core/tests/getPrimaryKeyTest.ts

Fixes https://github.com/aerogear/graphback/issues/1089
This fix prints custom directives to the final schema

fix: Print schema with directives

---

templates/ts-apollo-fullstack/.graphqlrc.yml
templates/ts-apollo-fullstack/server/src/graphql.ts

See https://github.com/aerogear/graphback/commit/673fce28a700d4ccc5ef72642a6226e446e61bb6#r38764338

fix: correct pass resolvers to ApolloServer

---

website/src/components/Terminal/index.jsx

it should be `npx graphback-cli init`.

docs(website): change CLI command name

---

docs/db/migrations.md
docs/intro/datamodel.md

Add information about how to define a many-to-many relationship.

docs(datamodel): add many-to-many documentation

---

packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
packages/graphback-runtime-knex/src/createKnexServices.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/queryBuilder.ts
packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
packages/graphback-runtime/src/data/GraphbackDataProvider.ts

This PR implements the new CRUD spec for MongoDB

Implement new crud for mongo

---

packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/queryBuilder.ts
packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts

This PR implements orderby for MongoDBDataProvider with accompanying tests and cleans up overall mongo provider testing in accordance with #1133 
Please take a look :)

Implement OrderBy for Mongo

---

integration/tests/runtime-workflow.ts

Fix the issue by making sure that there is no shared context between each test.
Previous after the first test is executed, subsequent tests were failing with the following message:
```
TypeError: Cannot redefine property: Symbol(apolloServerExecutionDispatcherWillResolveField)
at Function.defineProperty (<anonymous>)
at Object.<anonymous> (../node_modules/apollo-server-core/src/requestPipeline.ts:431:14)
at fulfilled (../node_modules/apollo-server-core/dist/requestPipeline.js:5:58)
```
While looking at the code, it seemed to me like the context we passed to apollo server was a global one and hence between multiple tests which resulted in a failure as we attempted to redifine a property that already was defined in the previous ran.

test: fix failing runtime-workflow integration tests

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
packages/graphback-codegen-schema/tests/mock.graphql
templates/ts-apollo-postgres-backend/src/schema/schema.graphql

fix: Initial version for generic scalar building

---

packages/graphback-cli/src/init/starterTemplates.ts

fix(templates): fix template paths

---

docs/plugins/graphback-client.md
docs/releases.md
integration/.graphqlrc.yml
integration/tests/runtime-workflow.ts
packages/graphback-codegen-client/src/ClientCRUDPlugin.ts
packages/graphback-codegen-client/src/helpers/writeDocuments.ts
packages/graphback-codegen-client/tests/GraphQLClientCreatorTest.ts
templates/ts-apollo-mongodb-backend/.graphqlrc.yml
templates/ts-apollo-postgres-backend/.graphqlrc.yml
templates/ts-apollo-postgres-backend/src/schema/schema.graphql

This PR modifies the client codegen to use specified `outputPath` as file path for output. This PR also contains Doc fixes

Production ready client generation

---

packages/graphback-runtime-mongodb/tests/queryBuilderTest.ts

Fixes https://github.com/aerogear/graphback/issues/1379

test: fix random mongo queryBuilder test failure

---

docs/intro/datamodel.md
docs/releases.md
packages/graphback-core/src/annotations/parser.ts
packages/graphback-core/src/db/getPrimaryKey.ts
packages/graphback-core/tests/buildModelTableMapTest.ts
packages/graphback-core/tests/dataMapperTest.ts
packages/graphback-core/tests/getPrimaryKeyTest.ts
packages/graphback-runtime-knex/tests/service/DefaultCRUDServiceTest.ts
packages/graphback-runtime/tests/LayeredRuntimeResolverCreatorTest.ts
packages/graphql-migrations/src/abstract/generateAbstractDatabase.ts
packages/graphql-migrations/tests/specs/abstract-database.ts

Fixes https://github.com/aerogear/graphback/issues/1322

feat(core): rename `@db.primary` to `@id` for better visibility

---

packages/graphback-core/src/crud/mappingHelpers.ts
packages/graphback-datasync/package.json
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/deltaMappingHelper.ts
packages/graphback-datasync/src/index.ts
packages/graphback-datasync/src/providers/DataSyncProvider.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-datasync/src/providers/createDataSyncServices.ts
packages/graphback-datasync/src/providers/index.ts
packages/graphback-datasync/src/services/DataSyncCRUDService.ts
packages/graphback-datasync/src/services/createDataSyncServices.ts
packages/graphback-datasync/src/services/index.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts
packages/graphback-runtime/src/service/CRUDService.ts

This PR adds soft deletion functionality to DataSyncMongoDBProvider

Add soft deletes for Mongo

---

.circleci/config.yml

Closes:
- https://github.com/aerogear/graphback/issues/1157
- https://github.com/aerogear/graphback/issues/1071
- https://github.com/aerogear/graphback/issues/1283
- https://github.com/aerogear/graphback/issues/1296
- https://github.com/aerogear/graphback/issues/1027
- https://github.com/aerogear/graphback/issues/1072
- https://github.com/aerogear/graphback/issues/1064
This PR changes significantly alters the runtime API to reduce overall complexity of configuring and using Graphback.
Essentially we have cut out a multi-step approach to configuring a Graphback server and made it into a single function API to create the services, resolvers, datasources and schema. Here is how simple it has become:
```ts
const { typeDefs, resolvers, services } = buildGraphbackAPI(modelDefs, { …
```

New runtime api

---

templates/ts-apollo-postgres-backend/package.json

Template was missing dependency not caught because of yarn workspaces

fix(deps): missing dependencies in template

---

packages/graphback-runtime/src/index.ts
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts
packages/graphback-runtime/src/service/GraphbackContext.ts
packages/graphback/src/buildGraphbackAPI.ts

The path to the Datasync service was wrong (my bad).
this is not easily verifiable unless we add a data sync template.

fix: wrong path to service property

---

packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts

The DataSync resolver was missing a call to the DataSync service

fix(resolvers): datasync service not being called

---

packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/DataSyncPluginTest.ts
packages/graphback/tests/buildGraphbackAPITest.ts

fix(datasync): remove plugin config for datasync plugin

---

templates/ts-apollo-mongodb-backend/src/index.ts
templates/ts-apollo-postgres-backend/src/index.ts

Load model independent of working dir.

fix: independent model loading

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-datasync/src/services/DataSyncCRUDService.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/DataSyncPluginTest.ts
packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts

This PR adds a filter argument to the sync query in the datasync package

Add ability to filter sync queries

---

templates/ts-apollo-mongodb-backend/src/index.ts
templates/ts-apollo-postgres-backend/src/index.ts

Reverts aerogear/graphback#1447

Revert "fix: independent model loading"

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
packages/graphback-codegen-schema/tests/mock.graphql

Fixes https://github.com/aerogear/graphback/issues/1452

fix(codegen-schema): filter on relationship when `@model.find` is false

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-core/src/crud/mappingHelpers.ts
packages/graphback-datasync/package.json
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/deltaMappingHelper.ts
packages/graphback-datasync/src/util.ts
packages/graphback-datasync/tests/DataSyncPluginTest.ts
packages/graphback-runtime-mongodb/src/queryBuilder.ts
packages/graphback-runtime-mongodb/tests/queryBuilderTest.ts
packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts

Move datasync resolvers to datasync plugin and other minor fixes

---

packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/util.ts

Following up with feedback from #1477

refactor(datasync): minor refactoring

---

packages/graphql-serve/src/GraphbackServer.ts

Fixes https://github.com/aerogear/graphback/issues/1468

fix: graphql-serve CRUD service not attached

---

docs/datasync/datasync-soft-delete.md
packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
packages/graphback-codegen-schema/src/index.ts
packages/graphback-datasync/README.md
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/util.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
packages/graphback-datasync/tests/mock.graphql
packages/graphback-runtime-mongodb/src/queryBuilder.ts
packages/graphback/tests/buildGraphbackAPITest.ts

Fix datasync using multiple annotations

---

integration/tests/runtime-workflow.ts
packages/graphback-codegen-client/src/templates/gqlTemplates.ts
packages/graphback-codegen-client/tests/__snapshots__/GraphQLClientCreatorTest.ts.snap
packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-core/src/runtime/CRUDService.ts
packages/graphback-core/src/runtime/GraphbackCRUDService.ts
packages/graphback-core/src/runtime/GraphbackDataProvider.ts
packages/graphback-core/src/runtime/interfaces.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-keycloak-authz/tests/KeycloakCrudService.test.ts
packages/graphback-keycloak-authz/tests/mocks/MockDataProvider.ts
packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
packages/graphback-runtime-knex/tests/service/DefaultCRUDServiceTest.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts

feat: return pagination info if requested

---

packages/graphback-cli/src/init/starterTemplates.ts

Fixes https://github.com/aerogear/graphback/issues/1483

fix(cli): `graphback init` throws an error when creating fullstack templates

---

packages/graphback-runtime-mongodb/package.json
packages/graphback-runtime-mongodb/src/utils/createIndexes.ts
packages/graphback-runtime-mongodb/tests/__util__.ts
packages/graphback-runtime-mongodb/tests/createIndexesTest.ts

fix: remove id indexes from mongo

---

templates/ts-apollo-mongodb-backend/package.json
templates/ts-apollo-postgres-backend/package.json

Fixes https://github.com/aerogear/graphback/issues/1543

chore(templates): add graphback-cli as dev dependency

---

packages/graphback-cli/src/init/starterTemplates.ts
packages/graphback-datasync/src/services/createDataSyncService.ts
templates/ts-apollo-mongodb-datasync-backend/.env
templates/ts-apollo-mongodb-datasync-backend/.gitignore
templates/ts-apollo-mongodb-datasync-backend/Dockerfile
templates/ts-apollo-mongodb-datasync-backend/README.md
templates/ts-apollo-mongodb-datasync-backend/client
templates/ts-apollo-mongodb-datasync-backend/docker-compose.yml
templates/ts-apollo-mongodb-datasync-backend/model/Note.graphql
templates/ts-apollo-mongodb-datasync-backend/package.json
templates/ts-apollo-mongodb-datasync-backend/src/db.ts
templates/ts-apollo-mongodb-datasync-backend/src/index.ts
templates/ts-apollo-mongodb-datasync-backend/tsconfig.json

This took a while to push :smile:

Datasync template

---

.vscode/launch.json
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts

Datasync minor fixes

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-datasync/src/DataSyncPlugin.ts

Reverts aerogear/graphback#1586

Revert "refactor: avoid creating a new context object when adding options"

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-core/src/runtime/CRUDService.ts
packages/graphback-core/src/runtime/GraphbackCRUDService.ts
packages/graphback-core/src/runtime/GraphbackDataProvider.ts
packages/graphback-core/src/runtime/GraphbackProxyService.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-keycloak-authz/src/KeycloakCrudService.ts
packages/graphback-keycloak-authz/tests/KeycloakCrudService.test.ts
packages/graphback-keycloak-authz/tests/mocks/MockDataProvider.ts
packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
packages/graphback-runtime-knex/tests/service/DefaultCRUDServiceTest.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts

Fixes https://github.com/aerogear/graphback/issues/1599

fix(crud): change order of arguments

---

docs/databases/introduction.md
docs/getting-started/adding-graphback-to-your-project.md
docs/getting-started/creating-a-new-application.md
docs/intro-to-graphback.md
docs/model/your-datamodel.md
website/docusaurus.config.js
website/sidebars.json

docs(getting-started): getting started section

---

docs/.old/intro/graphqlserve.md
docs/.old/releases.md
packages/graphql-serve/README.md
packages/graphql-serve/package.json
packages/graphql-serve/src/commands/serve.ts

Fixes https://github.com/aerogear/graphback/issues/1648

fix: graphqlserve has invalid doc command

---

integration/package.json
integration/tests/runtime-workflow-mongo.ts
integration/tests/runtime-workflow-postgres.ts

Fixes failing integration tests in [jobs/5744](https://app.circleci.com/pipelines/github/aerogear/graphback/5629/workflows/07663b62-8eff-4f4a-8c1d-778e65db871b/jobs/5744/steps)

build: use graphql-tools to load files

---

docs/graphql-migrations/db-design.md
docs/graphql-migrations/plugins.md

docs(website): add how to use plugins in graphql migrations

---

packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/queryBuilder.ts

fixes #1603 
Please take a look :D

fix: add ability to keep custom updatedAt and createdAt

---

docs/crud/mutations.md
docs/crud/queries.md
docs/crud/subscriptions.md

docs: add CRUD subscriptions section

---

docs/plugins/client-crud-plugin.md
docs/plugins/overview.md
docs/plugins/schema-crud-plugin.md
templates/ts-apollo-postgres-backend/.graphqlrc.yaml
website/sidebars.json

Adds documentation for SchemaCRUDPlugin, ClientCRUDPlugin

docs: add ClientCRUD/SchemaCRUD plugin docs

---

docs/plugins/client-crud-plugin.md

Leftover from https://github.com/aerogear/graphback/pull/1690/files#r452053154

docs(website): fix codgen client package name

---

packages/graphback-core/src/plugin/GraphbackPlugin.ts

Follows up https://github.com/aerogear/graphback/pull/1706#issuecomment-657463518

refactor(plugin): make GraphbackPlugin#createResources non abstract

---

packages/graphback-cli/src/index.ts

Fixes https://github.com/aerogear/graphback/issues/1720
Quickly opened this PR to get feedback, see the linked issue for comments. Hoping to get this merged soon.

fix(graphback-cli-api): expose generateUsingPlugins as public API

---

package.json

chore: add datasync templates to workspace

---

docs/releases.md
packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts
packages/graphback-core/src/crud/mappingHelpers.ts
packages/graphback-core/tests/scalarsTest.ts

Fixes https://github.com/aerogear/graphback/issues/1604

fix(core): throw an error if relationship annotation are missing

---

packages/create-graphback/src/init/starterTemplates.ts

fix(create-graphback): fix issue with generating a fullstack template

---

website/docusaurus.config.js
website/package.json

Temporary workaround fix for https://github.com/facebook/docusaurus/issues/3136#issuecomment-665662134

fix(docs): ignore broken links in docusaurus

---

packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts

This is causing a failing test on master.

test: remove invalid directive from object

---

packages/graphback/src/buildGraphbackAPI.ts

Fixes https://github.com/aerogear/graphback/issues/1813

fix: make sure that `options` is initialised in Graphback context

---

docs/datasync/soft-delete.md
integration/datasync-mongodb-model.graphql
integration/tests/runtime-workflow-datasync.ts
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/providers/DataSyncProvider.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-datasync/src/services/DataSyncCRUDService.ts
packages/graphback-datasync/src/util.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/DataSyncPluginTest.ts
packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap

~This PR restores the `_version` field that was present in offix-plugin in previous release~
`_version` will be properly added along with conflicts in the next PR
This PR only adds `_lastUpdatedAt` and removes update conflicts from default configuration

[DataSync] add datasync specific _lastUpdatedAt

---

docs/releases.md

docs: add release notes for datasync

---

packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
packages/graphback-codegen-schema/tests/mock.graphql

Adding a snapshot test to have this area covered and avoid regressing in the future.

test(schema-plugin): add a test case for directives that uses enums

---

packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-core/src/runtime/CRUDService.ts
packages/graphback-runtime-knex/tests/service/DefaultCRUDServiceTest.ts

Fixes https://github.com/aerogear/graphback/issues/1859

fix: add a null / undefined check before loading relationship with dataloader and make sure that relationship field is loaded in these cases

---

docs/releases.md
packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
packages/graphback-codegen-schema/tests/mock.graphql

Fixes https://github.com/aerogear/graphback/issues/1349

feat(schema-plugin): use GraphbackDateTime scalar for generated createdAt updatedAt fields

---

packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap

Fixes https://github.com/aerogear/graphback/issues/1825

feat: create index for the lastUpdateAt field

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-help.md

chore: add github issue templates

---

integration/datasync-mongodb-model.graphql
integration/tests/runtime-workflow-datasync-conflicts.ts
packages/graphback-datasync/src/deltaSource.ts
packages/graphback-datasync/src/providers/DataSyncConflictProvider.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-datasync/src/util.ts
packages/graphback-datasync/tests/DataSyncConflictProviderTest.ts
packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
packages/graphback-datasync/tests/DataSyncPluginTest.ts
packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
templates/ts-apollo-mongodb-datasync-backend/model/Note.graphql
templates/ts-apollo-mongodb-datasync-backend/src/index.ts

[WIP]feat(datasync): add TTL

---

packages/graphback-core/src/runtime/createInMemoryFilterPredicate.ts
packages/graphback-core/src/scalars/index.ts
packages/graphback-core/src/scalars/objectId.ts

Follows https://github.com/aerogear/graphback/pull/1870/files#r472129139

fix: always prefer bson-ext if it is installed over bson

---

website/sidebars.json

Fixes https://github.com/aerogear/graphback/issues/1823
Kudos @ssd71 for initiating the work.
Co-authored-by: Shibani Shankar Dash <shibanidash71@gmail.com>

docs(api-reference): put api reference docs in sections

---

docs/crud/queries.md
docs/model/scalars.md
docs/releases.md
packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
packages/graphback-core/src/runtime/QueryFilter.ts

fix(schema): missing Date filters

---

docs/datasync/conflict-resolution-intro.md
docs/datasync/conflict-resolution-strategies.md
integration/tests/runtime-workflow-datasync-conflicts.ts
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/helpers/createDataSync.ts
packages/graphback-datasync/src/providers/createDataSyncMongoDbProvider.ts
packages/graphback-datasync/src/util.ts
packages/graphback-datasync/tests/DataSyncConflictProviderTest.ts
packages/graphback-datasync/tests/DataSyncPluginTest.ts
packages/graphback-datasync/tests/getModelConfigTest.ts
packages/graphql-serve/src/runtime.ts
templates/ts-apollo-mongodb-datasync-backend/src/index.ts

This PR adds global conflict configuration for datasync
fixes #1902

feat(datasync): add global conflict configuration

---

packages/create-graphback/package.json
packages/graphback-cli/package.json
packages/graphback-codegen-client/package.json
packages/graphback-codegen-schema/package.json
packages/graphback-core/package.json
packages/graphback-datasync/package.json
packages/graphback-keycloak-authz/package.json
packages/graphback-runtime-knex/package.json
packages/graphback-runtime-mongodb/package.json
packages/graphback/package.json
packages/graphql-migrations/package.json
packages/graphql-serve/package.json

Add GitHub URL to npm package configs

---

packages/graphback-codegen-schema/package.json
packages/graphback-core/package.json
packages/graphback-datasync/package.json
packages/graphback-runtime-mongodb/package.json
packages/graphql-migrations/package.json

Follows up on https://github.com/aerogear/graphback/issues/1878#issuecomment-675292340

chore(deps): update graphql-metadata to 0.7.4

---

packages/graphback-core/package.json

Fixes https://github.com/aerogear/graphback/issues/1915
/cc @Eunovo maybe this will fix the issue for you.

chore(deps): add bson types

---

packages/graphback-core/src/runtime/createInMemoryFilterPredicate.ts
packages/graphback-core/tests/createInMemoryFilterPredicateTest.ts

Fixes https://github.com/aerogear/graphback/issues/1941

fix(subscription): cannot read property 'and' of "undefined" subscription filter

---

.github/workflows/build-website.yml
.github/workflows/graphback-ci.yml
docs/intro-to-graphback.md

This is based on https://v2.docusaurus.io/docs/deployment/#triggering-deployment-with-github-actions
Fixes https://github.com/aerogear/graphback/issues/1945

ci: auto-deploy website on push to master

---

.github/workflows/build-website.yml
.github/workflows/graphback-ci.yml

Previous it was deploying from the project root folder while it should deploy from the website
folder

ci: fix the commands that test website build and the one deploy the website

---

docs/datasync/conflict-resolution-strategies.md
packages/graphback-datasync/src/DataSyncPlugin.ts
packages/graphback-datasync/src/util.ts
packages/graphback-datasync/tests/DataSyncConflictProviderTest.ts
packages/graphql-serve/src/commands/serve.ts
packages/graphql-serve/src/runtime.ts

[DataSync] Add throwOnConflict strategy and check for validity for conflictConfig

---

integration/tests/runtime-workflow-mongo.ts
integration/tests/runtime-workflow-postgres.ts
packages/graphback-datasync/src/services/DataSyncCRUDService.ts

This follows up some feedback in https://github.com/aerogear/graphback/pull/1944

follow up to #1944

---

packages/create-graphback/src/index.ts
packages/graphback-cli/src/index.ts

Relates to and needed by https://github.com/aerogear/graphback/issues/1736

feat: expose commands from various cli

---

templates/ts-apollo-mongodb-backend/README.md
templates/ts-apollo-mongodb-datasync-backend/README.md
templates/ts-apollo-postgres-backend/README.md
templates/ts-react-apollo-client/README.md

Adds a project structure section describing what's contained in the templates. 
Open as an early PR to get fast feedback and we can iterate on this.

docs(templates): update templates README

---

.vscode/launch.json
integration/__util__/mongoUtil.ts
integration/tests/runtime-workflow-datasync-conflicts.ts
integration/tests/runtime-workflow-datasync.ts
integration/tests/runtime-workflow-mongo.ts
integration/tests/runtime-workflow-postgres.ts
packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
packages/graphback-runtime-mongodb/src/queryBuilder.ts
packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
packages/graphback-runtime-mongodb/tests/__util__.ts
packages/graphback-runtime-mongodb/tests/queryBuilderTest.ts

This PR was originally created to fix https://github.com/aerogear/graphback/issues/1963 but I found it difficult to fix with current format without breaking other areas.
`title startsWith "[DRAFT]" || title endsWith "[DRAFT]"`
```graphql
query {
findNotes(filter: {
title: {
startsWith: "[DRAFT]"
},
or: [
{
title: {
endsWith: "[DRAFT]"
}
]
}) {
items {
title
description
}
}
}
```
`title startsWith "[DRAFT]" || title endsWith "[DRAFT]"`
```graphql
query {
findNotes(filter: {
or: [
{
title: {
startsWith: "[DRAFT]"
}
},
{
title: {
endsWith: "[DRAFT]"
}
}
]
}) {
items {
title
description
}
}
}
```
`(title startsWith "[DRAFT]" && description eq "draft 3") || title endsWith "[DRAFT]"`
```graphql
query {
findNotes(filter: {
or: [
{
title: {
startsWith: "[DRAFT]"
},
description: {
eq: "draft 3"
} …
```

Refactor MongoDB queryBuilder

---

packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
packages/graphback-runtime-knex/src/SQLiteKnexDBDataProvider.ts
packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts

Round of database perf analysis as par https://github.com/aerogear/graphback/issues/1758

Review data providers

---

packages/create-graphback/src/init/starterTemplates.ts

@machi1990 @wtrocki going to prepare for an rc1 release tomorrow.

chore: update templates release branch to v1

---

docs/datasync/conflict-resolution-intro.md
docs/datasync/delta-queries.md
website/versioned_docs/version-0.16.x/datasync/conflict-resolution-intro.md
website/versioned_docs/version-0.16.x/datasync/delta-queries.md

Update data sync docs to suggest using the DataSync template

docs(datasync): set correct template

---

packages/graphback/README.md

README for `graphback` package was extremely out of date.

docs(graphback): updated outdated README outdated

---

docs/databases/introduction.md

I solved the Issue no. :  #2127

Fixed the 'Overiew' typo to 'Overview'

---

website/versioned_docs/version-0.14.x/databases/introduction.md
website/versioned_docs/version-0.15.x/databases/introduction.md
website/versioned_docs/version-0.16.x/databases/introduction.md
website/versioned_docs/version-1.0/databases/introduction.md

fixed typo in the sidebar

---

website/docusaurus.config.js
website/src/css/custom.css

feat: Replace top nav github label with logo

---

packages/create-graphback/src/init/components.ts

- Replaced graphback init with create-graphback
- Added chalk.cyan for code snippet
Fixes #2142

Edited graphback init message

---

website/blog/2020-10-01-announcing-graphback-1.0.md

This fixes an unfinished sentence in the announcement blog post

Fix unfinished sentence in blog post

---

.github/PULL_REQUEST_TEMPLATE.md

Added a line to specify the issue the PR fixes (if applicable) and added a note regarding removing stuff from template.
If some edits need to be made to the note please let me know. Thanks.

chore(pr-template): added a few details

---

packages/graphback-datasync/tests/__util__.ts
packages/graphback-runtime-mongodb/tests/__util__.ts
packages/graphql-serve/src/runtime.ts

chore: replace .getconnectionstring() with .getUri().

---

docs/model/annotations.md

Resolves #2181 
This PR removes invalid documentation from the annotation reference guide.

docs(annotations): remove invalid argument from oneToOne

---

docs/authentication/authentication.md
docs/authentication/keycloak.md
website/versioned_docs/version-0.14.x/authentication/authentication.md
website/versioned_docs/version-0.14.x/authentication/keycloak.md
website/versioned_docs/version-0.15.x/authentication/authentication.md
website/versioned_docs/version-0.15.x/authentication/keycloak.md
website/versioned_docs/version-0.16.x/authentication/authentication.md
website/versioned_docs/version-0.16.x/authentication/keycloak.md
website/versioned_docs/version-1.0/authentication/authentication.md
website/versioned_docs/version-1.0/authentication/keycloak.md

Fixes: #2187 
The typo was present in some other line too so I've fixed that also.
EDIT: Mentioned issue in PR

docs(website): Fix misspelling "Autorization" in Keycloak section

---

.gitignore

fixes:#2186
I replicated your repo structure and created a test folder with many sub-folders. I then manually added sqlite files into them and tested whether they are getting ignored or not. I successfully verified it in the git status that sqlite files all over the repo were ignored.

fix:ignore sqlite files(#2186)

---

templates/ts-react-apollo-client/README.md

The readme stated that in order to run the client side one should run ```yarn start:client```, however this did not work for me and I had to run ```yarn start``` in the client directory to get the client running. If this was an issue on my machine then we can revert back else I've updated the part about running the client in the README too.
P.S. Sorry I commited using ```chore``` instead of ```docs``` accidently.

docs(client-template): fixed errors in README

---

renovate.json

I updated package rules to set automerge enabled for minor and patch updates.
- [ x] I have read the [CONTRIBUTING](https://github.com/aerogear/graphback/blob/master/CONTRIBUTING.md) document.

chore: enable auto-merge for minor and patch updates #2194

---

renovate.json

disable automerge

---

templates/ts-apollo-mongodb-backend/model/datamodel.graphql

fix: remove 'roles'

---

website/versioned_docs/version-1.0/crud/mutations.md
website/versioned_docs/version-1.0/crud/queries.md

Fixed a couple of minor errors in the website's documentation.

docs(website): minor fixes in docs

---

website/package.json

Reverted the dependency updates done by PR #2167 in website/package.json

fix(deps): revert back changes in website/package.json

---

COMMUNITY-TEMPLATES.MD

This is a minor fix but can be helpful for future contributors.
While adding a new community template to Graphback, it took me a little extra time to locate the communityTemplates.ts file since the exact path was not mentioned in the readme due to which I had to browse through every folder and their sub-folders in the `packages` directory to find that file. 
Through this PR, I have updated the readme to point to the exact location of the file.

docs(community-templates): add exact path to the communityTemplates.ts file

---

COMMUNITY-TEMPLATES.MD

Added a link to the communityTemplates.ts file.
In response to: https://github.com/aerogear/graphback/pull/2255#discussion_r555602074

docs(community-templates): add link to communityTemplates.ts file

---

COMMUNITY-TEMPLATES.MD

Updated the communityTemplates.ts file link to use a relative path.
In response to: https://github.com/aerogear/graphback/pull/2257#discussion_r556365337

docs(community-templates): update file link with a relative path

---

packages/create-graphback/src/init/starterTemplates.ts

Fixes an error:
```sh
TypeError: parse_github_url_1.default is not a function
at getTemplateRepositoryTarInformation (/home/ephelan/go/src/github.com/aerogear/graphback/packages/create-graphback/dist/init/starterTemplates.js:119:44)
at Object.<anonymous> (/home/ephelan/go/src/github.com/aerogear/graphback/packages/create-graphback/dist/init/starterTemplates.js:179:29)
at Generator.next (<anonymous>)
at /home/ephelan/go/src/github.com/aerogear/graphback/packages/create-graphback/node_modules/tslib/tslib.js:115:75
at new Promise (<anonymous>)
at Object.__awaiter (/home/ephelan/go/src/github.com/aerogear/graphback/packages/create-graphback/node_modules/tslib/tslib.js:111:16)
at Object.extractTemplate (/home/ephelan/go/src/github.com/aerogear/graphback/packages/create-graphback/dist/init/start …
```

fix: import format was throwing an error

---

packages/create-graphback/src/init/communityTemplates.ts

Added metadata of a newly created NestJS server template to the `communityTemplates.ts` file.
Fixes #2212

feat(packages): add a NestJS community template

---

packages/create-graphback/src/init/communityTemplates.ts

Came across this error while initializing a project using the NestJS community template:
```python
CwdError: ENOENT: Cannot cd into '/home/namit/Projects/graphback/packages/create-graphback/testProject'
at /home/namit/Projects/graphback/packages/create-graphback/node_modules/tar/lib/mkdir.js:100:17
at FSReqCallback.oncomplete (fs.js:171:23) {
path: "/home/namit/Projects/graphback/packages/create-graphback/testProject",
code: 'ENOENT'
}
```
Through this PR, I have added the necessary fix for it.

fix(packages): fix ENOENT error in NestJS template

---

docs/resolvers/custom-resolvers.md
website/versioned_docs/version-0.16.x/resolvers/custom-resolvers.md
website/versioned_docs/version-1.0/resolvers/custom-resolvers.md

Updates the docs to reflect the accuracy of the args for the CRUD service `findBy` method
- [N/A] Lint and unit tests pass locally with my changes
- [N/A] I have added tests that prove my fix is effective or that my feature works
--

docs: update code sample for N+1 queries for graphback crud service findBy method
