- templates/apollo-starter-ts/README.md
#17 Add the following template structure
```
|-----generated
|-----schema.graphql
|-----resolvers.ts
|-----model
|-----<your-model-name>.graphql
|-----src
|-----config
|-----config.ts
|-----db.ts
|-----index.ts
|-----mapping.ts
|-----package.json
|-----Dockerfile
|-----docker-compose.yml
|-----package-lock.json
|-----tslint.json
|-----README.md
```
> fix: add project structure to readme

- packages/graphback-cli/src/templates/resources/docker/pg-docker-compose.yml
- packages/graphback/src/resolvers/knex/resolverImplementation.ts
- packages/graphback/src/resolvers/knex/targetResolverContext.ts
- packages/graphback/src/resolvers/resolverTemplate.ts
- templates/apollo-starter-ts/package.json
- templates/apollo-starter-ts/src/index.ts
- templates/apollo-starter-ts/src/subscriptions.ts
For each type generate
- `new`
- `updated`
- `deleted`
Use redis pubsub for subscription
For input
```
type Note {
id: ID!
title: String!
description: String!
}
```
the output resolver file
```
enum Subscriptions {
NEW_NOTE = 'newnote',
UPDATED_NOTE = 'updatednote',
DELETED_NOTE = 'deletednote'
}
export const resolvers = {
Query: {
findNotes: (_, args, context) => {
return context.db.select().from('note').where(args.fields)
},
findAllNotes: (_, __, context) => {
return context.db.select().from('note')
}
},
Mutation: {
createNote: async (_, args, context) => {
const result = await context.db('note').insert(args.input).returning('*')
context.pubsub.publish(Subscriptions.NEW_NOTE, {
newNote: result[0]
})
return result[0]
},
updateNote: (_, args, context) => {
return …
```
> Implement Subscriptions resolvers

- templates/apollo-starter-ts/package.json
Currently `npm start` runs the built js files. Since `graphback watch` runs `npm start`(currently not working as rebuild is not done),
- changed `start` script to `ts-node`
- add `serve` script for built files
> fix: change scripts

- docs/working.md
Feedback provided shown us that we are missing critical parts of the docs and it is not clear how graphback works. This should do the job.
> fix: add missing documentation

- packages/graphback-cli/package.json
- packages/graphback/src/resolvers/knex/resolverImplementation.ts
- packages/graphback/src/resolvers/knex/targetResolverContext.ts
- packages/graphback/src/resolvers/resolverTemplate.ts
- packages/graphback/src/schema/targetSchemaContext.ts
Added relationships info to schema generation
```
type Note {
id: ID!
title: String!
description: String!
comment: [Comment]!
}
type Comment {
id: ID!
title: String!
description: String!
}
```
output schema looks like
```
type Note {
id: ID!
title: String!
description: String!
comment: [Comment]!
}
type Comment {
id: ID!
title: String!
description: String!
noteId: ID!
}
input NoteInput {
title: String!
description: String!
}
input CommentInput {
title: String!
description: String!
noteId: ID!
}
input NoteFilter {
id: ID
title: String
description: String
}
input CommentFilter {
id: ID
title: String
description: String
noteId: ID
}
......
```
Changes in output resolvers
```
Note: {
comments: (parent: any, _: any, context: GraphQLContext) => {
return …
```
> Relation support in graphback

- docs/working.md
- packages/graphback-cli/src/templates/starterTemplates.ts
- templates/apollo-rest-starter/.dockerignore
- templates/apollo-rest-starter/.gitignore
- templates/apollo-rest-starter/.template.json
- templates/apollo-rest-starter/Dockerfile
- templates/apollo-rest-starter/README.md
- templates/apollo-rest-starter/generated/resolvers.ts
- templates/apollo-rest-starter/generated/schema.ts
- templates/apollo-rest-starter/package.json
- templates/apollo-rest-starter/src/config/config.ts
- templates/apollo-rest-starter/src/context.ts
- templates/apollo-rest-starter/src/db.ts
- templates/apollo-rest-starter/src/index.ts
- templates/apollo-rest-starter/src/mapping.ts
- templates/apollo-rest-starter/src/subscriptions.ts
- templates/apollo-rest-starter/tsconfig.json
- templates/apollo-rest-starter/tslint.json
Not everyone is fully into GraphQL. While using DSL as a way to model data seems very cool and people like it sometimes there is need to use rest for some clients where GraphQL cannot be used (embedded etc.) Adding new template that will offer both REST and GraphQL options. index.ts has main changes.
We are using here Sofa from @urigo that makes this task very simple. 
Going to follow up with testing this template with production ready schemas we have to see how this plays up and if we need to add much more later.
```
npm run start
curl http://localhost:4000/rest/me
```
> Sofa integration

- packages/graphback-cli/package.json
- packages/graphback-cli/src/templates/resources/models/Note.graphql
- packages/graphback/src/InputTypeVisitor.ts
- packages/graphback/src/directives.ts
```
type Test @update {
.....
}
```
will enable the operation while
```
type Test @update(enable: false) {
.....
}
```
will disable the operation.
> fix: disable option in directives

- packages/graphback-cli/src/templates/resources/models/Tasks.graphql
This (chore) uses the new `@disableGen` directive in the `Tasks.graphql` schema.
> Adds disableGen to type CreationMetadata

- docs/clientsidequeries.md
- packages/graphback-cli/src/helpers/generate.ts
- packages/graphback-cli/src/helpers/init.ts
- packages/graphback-cli/src/templates/configTemplates.ts
- packages/graphback/example/Note.graphql
- packages/graphback/src/GraphQLBackend.ts
- packages/graphback/src/client/index.ts
- packages/graphback/src/client/targetContext.ts
- packages/graphback/src/index.ts
- packages/graphback/src/resolvers/outputResolvers/resolverTemplate.ts
- website/i18n/en.json
- website/sidebars.json
Generate queries and mutation with fragments according to config(which are enabled). #72 
```
import gql from "graphql-tag"
import { NoteFragment } from "../fragments/Note"
export const updateNote = gql`
mutation updateNote($id: ID!, title: String!, description: String!, published: Boolean!) {
updateNote(id: $id, input: {title: $title, description: $description, published: $published}) {4
...NoteFields
}
}
${NoteFragment}
`
```
```
import gql from "graphql-tag"
import { NoteFragment } from "../fragments/Note"
export const findAllNotes = gql`
query findAllNotes {
findAllNotes {
...NoteFields
}
}
${NoteFragment}
`
```
```
import gql from "graphql-tag"
import { CommentFragment } from "../fragments/Comment"
export const newComment = gql`
subscription newComment {
newComment {
...CommentFields …
```
> Generate client queries based on datamodel

- packages/graphback-cli/src/helpers/init.ts
- packages/graphback-cli/src/templates/starterTemplates.ts
GraphQL-JS template never worked due to resolver issues. At this point, it makes no sense to build separate resolvers for that. We need to think more deeply what the desired architecture we want for the graphback core, but with this week end of GSOC let's keep all features functional
> fix: disable js template

- CHANGELOG.md
- docs/releases.md
- lerna.json
- package-lock.json
- packages/graphback-cli/package.json
- packages/graphback-cli/src/helpers/init.ts
- packages/graphback-cli/src/templates/resources/docker/postgres.yml
- packages/graphback-cli/src/templates/resources/models/Note.graphql
- packages/graphback/package.json
- templates/apollo-rest-starter/package.json
- templates/apollo-rest-starter/src/context.ts
- templates/apollo-rest-starter/src/subscriptions.ts
- templates/apollo-starter-ts/package.json
- templates/apollo-starter-ts/src/context.ts
- templates/apollo-starter-ts/src/subscriptions.ts
- templates/graphql-js-starter/package.json
Change code in templates for in-memory subscriptions to use `graphql-subscriptions`. Removed dependency of redis in docker.
> Remove redis dependency for subscriptions

- templates/apollo-rest-starter/config.json
- templates/apollo-starter-ts/config.json
- templates/graphql-js-starter/config.json
https://github.com/aerogear/graphback/issues/292
1. From each template directory, run `graphback generate`.
2. Resolvers should have been generated.
> fix(config.json): add CRUD config by default to templates

- packages/graphback-cli/src/helpers/db.ts
Replace watch command with develop. For long term we should have detached run process from the template - for now we can just say that each template needs develop command.
> fix: Replace watch with develop

- CONTRIBUTING.md
This change fixed a badly formatted hyperlink, which appeared to be using the Asciidoc format.
This change also fixed a typo, and some Markdown linting warnings.
> fix: broken docs link

- docs/releases.md
Every change we do - skipping some trivial ones will need to land into release notes.
There is no need for documentation for this feature.
> fix: Add documentation for interface support

- docs/clientsidequeries.md
I believe the `4` was not meant to be there
> typo: remove 4 from the doc

- packages/graphback/src/ContextCreator.ts
- packages/graphback/src/ContextTypes.ts
- packages/graphback/src/utils/index.ts
#331 
- Modified visited output to combine `ObjectTypeDefinition` and `ObjectTypeExtension` nodes.
- Use type extension in model
```
type Note {
title: String
}
extend type Note {
description: String
}
```
- Run `graphback generate` and check for duplication in schema as in #331
> fix: duplicate schema in type extension

- packages/graphback-cli/src/index.ts
feat: check if the command exits or if enough arguments have been passed.
#348 
Check:
- Link graphback-cli
- Use graphback with command `graphback start` should produce an error.
- Use graphback with no commands should provide the same output as usual with 
`Not enough non-option arguments: got 0, need at least 1` 
- Everything else works as normal
> feat: unrecognized commands throw an error

- packages/graphback-cli/src/templates/resources/models/Shop.graphql
- packages/graphback/src/resolvers/knex/targetResolverContext.ts
#360 
Leaving it as a draft for now as I'm still investigating whether that's a solution for the issue
Issue before:
When for example Shop had an attribute of type of another entity it would generate resolver for that entity also. Creating ` *:* ` relationship out of ` 1:* ` causing it to fail.
Fix:
Given above schema our person resolvers look like this now:
and shop resolvers :
> fix: creating unnecesarry types

- packages/graphback-cli/src/index.ts
Due to cheatsheet: https://devhints.io/yargs
Resolves: #366, #367
> Add CLI shorthands (aliases) for --help and --version

- packages/graphback/src/layers/data/KnexDBDataProvider.ts
- packages/graphback/tests/layers/data/sqlite_in_memory_data_provider_test.ts
Create and update tests are failing:
```
⠴ .returning() is not supported by sqlite3 and will not have any effect.
⠦ .returning() is not supported by sqlite3 and will not have any effect.
2 tests failed
update Todo
/home/dbizzarr/Projects/github.com/aerogear/graphback/packages/graphback/src/layers/data/KnexDBDataProvider.ts:39
38:         }                                              
39:         throw new NoDataError(`Cannot update ${name}`);
40:     }                                                  
Rejected promise returned by test. Reason:
Error (NoDataError) {
message: 'No result from database: Cannot update todos',
}
KnexDBDataProvider.<anonymous> (src/layers/data/KnexDBDataProvider.ts:39:15)
fulfilled (node_modules/tslib/tslib.js:107:62)
create Todo …
```
> chore: add tests for sqlite in-memory data provider

- packages/graphback-cli/src/templates/starterTemplates.ts
Use a separate branches (not master) for templates to avoid breaking changes. 
This is important now that we do not plan other templates to be available and we want current releases to work.
> fix: Use templates-master branch for next release

- scripts/validateRelease.sh
The old `awk` piped command was cutting the version at the next `v`, I've copied this new command from the offix project: https://github.com/aerogear/offix/blob/550802ff97077b62d850786138f898a0dbc3ea92/scripts/validateRelease.sh#L27
> fix: validate release script when releasing dev

- examples/generator-example/package.json
- packages/graphback-cli/tests/workflow-test.ts
- packages/graphback-db-manage/package.json
Integration test was not executing because the incorrect SQLite database connection options were being provided.
Tests never failed, because they were never executed.
1. `cd packages/graphback-cli`
2. `npm run test`
3. Tests pass.
> Fix integration test

- docs/custom.md
- examples/generator-fullstack/server/package.json
- examples/generator-fullstack/server/src/index.ts
- examples/runtime-example/src/runtime.ts
- packages/graphback-codegen-resolvers/src/api/targetResolverContext.ts
- packages/graphback-codegen-resolvers/src/templates/LayeredResolverTemplates.ts
- packages/graphback-runtime/src/GraphbackRuntimeOptions.ts
- packages/graphback-runtime/src/createKnexRuntimeContext.ts
- packages/graphback-runtime/src/data/GraphbackDataProvider.ts
- packages/graphback-runtime/src/data/KnexDBDataProvider.ts
- packages/graphback-runtime/src/index.ts
- packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverGen.ts
- packages/graphback-runtime/src/service/CRUDService.ts
- packages/graphback-runtime/src/service/GraphbackCRUDService.ts
- packages/graphback-runtime/tests/service/DefaultCRUDServiceTest.ts
- packages/graphback/src/GraphQLBackendCreator.ts
- website/blog/2019-08-27-crash-course-on-graphback.md
Support subscriptions for both runtime and generated source code. 
I have added extra parameter to the service layer that can determine runtime options. 
For example developers might decide after to not publish change to subscriptions. 
There are two types here:
GraphbackRuntimeOptions - runtime options and modifiers triggered on resolver level
GraphbackRuntimeContext - global context with applied service etc.
```
subscription subtest {
newNote{
id
title
description
}
```
> Runtime subscription

- examples/generator-fullstack/graphback.json
- examples/runtime-example/src/runtime.ts
- packages/graphql-migrations/src/DatabaseMigrater.ts
- packages/graphql-migrations/src/database/initialization/strategies/UpdateDatabaseIfChanges.ts
- packages/graphql-migrations/src/migrations/KnexMigrationManager.ts
- packages/graphql-migrations/src/migrations/KnexMigrationProvider.ts
- packages/graphql-migrations/src/migrations/LocalMigrationManager.ts
- packages/graphql-migrations/src/migrations/SchemaMigration.ts
Fixes https://github.com/aerogear/graphback/issues/495
Change the ID type of `SchemaMigration` to match the ID type in the database.
Postgres migrations should work as before.
1. Install sqlite3 to the runtime example.
2. Change database configuration to:
```
"db": {
"database": "sqlite3",
"dbConfig": {
"filename": "./db.sqlite"
}
},
```
3. Executing migrations with SQLite should now work.
> Change `SchemaMigration` ID type to number

- examples/runtime-example/model/runtime.graphql
- packages/graphql-migrations/src/DatabaseMigrater.ts
- packages/graphql-migrations/src/index.ts
- packages/graphql-migrations/src/migrations/KnexMigrationManager.ts
- packages/graphql-migrations/src/migrations/KnexMigrationProvider.ts
- packages/graphql-migrations/src/migrations/SchemaMigration.ts
- packages/graphql-migrations/src/migrations/utils.ts
- packages/graphql-migrations/tests/DatabaseMigrater.test.ts
Closes https://github.com/aerogear/graphback/issues/481
Migrations were not executing because reading the migration table with Knex was not mapping the ID column back to an number. This meant that local migrations were different to remote and it tried to create the migration twice, which failed.
This change also allows migrations to be executed when only local migration data exists.
1. Run 2 migrations using the runtime-example. Everything should work.
2. Delete both migrations from the `gb_schema_migrations` table and delete the changes that were applied in them.
3. Now you should have two migrations on your local filesystem. Run the runtime example again.
4. Both of these migrations should be applied.
> Fix failed migration execution

- packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverGen.ts
I believe this is what I need to fix my issue: https://github.com/aerogear/graphback/issues/536
Based on @b1zzu PR from here: https://github.com/aerogear/graphback/pull/523 this is just a corrected version with a argument name that is not a build in keyword.  Build now succeeds.
> Add one to many to runtime resolvers

- examples/runtime-example/model/runtime.graphql
This is a quick change to the default example model in `runtime-example`.
> Change the example model in `runtime-example`

- docs/database-schema-migrations.md
- examples/runtime-example/src/runtime.ts
- packages/graphback-cli/src/helpers/db.ts
- packages/graphql-migrations/README.md
- packages/graphql-migrations/src/index.ts
- packages/graphql-migrations/src/migrate.ts
- packages/graphql-migrations/src/production/migrations/GraphQLMigrationCreator.ts
https://github.com/aerogear/graphback/issues/552
Change the public API methods in `graphql-migrations`.
- migrate: migrateDB
- runGraphqlMigration: migrateProduction
> feat: change public API methods in `graphql-migrations`

- packages/graphback-runtime/src/data/KnexDBDataProvider.ts
When Knex queries a database a nunber may be returned as a string, so in order to check if "1" === 1 we should make them a common data-type.
> Compare ID values as strings

- packages/graphql-migrations/README.md
The `schema` type in `migrateDB` is string, docs used `GraphQLSchema`.
> docs: type should be string

- README.md
It makes much sense for the respective badge lead to contributing guidelines instead.
> [Docs]: update badge reference

- docs/database-schema-migrations.md
Documentation was not up to date and provided inaccurate information. Added a link to the relationships documentation to show how to customise foreign key field names.
> docs(db): add link to relationships docs

- renovate.json
Trying to test it. Not sure if that will work. basically this should cover rules for the path and override defaults from renovate
> fix: Include examples for renovate

- examples/runtime-example/src/runtime.ts
This simple fix will allow runtime example to work across different knex versions. 
Package bumps by renovate fixed in other PR will also make sure that we always use the same
Resolves https://github.com/aerogear/graphback/issues/619
> chore: Using any as config to not break knex types

- examples/runtime-example/README.md
The provided link was not working. 
I am not sure about the pointed line number in use in this PR (line 32). Is this the correct one?  
@wtrocki
> docs: update the url pointing to a fully functional runtime creation example

- examples/runtime-example/README.md
- examples/runtime-example/src/runtime.ts
- fix the type error in the `runtime.ts` file in the runtime-example app, as discussed in the standup this morning.
- improve the docs to include the correct steps for starting up the server and add instructions for using sqllite 3 in the runtime-example app
> fix: fix type error in runtime example & improve runtime-example docs

- packages/graphback-codegen-schema/src/plugin/SchemaCRUDPlugin.ts
Subscriptions should not be generated if the CRUD config value for that operation type is `false`.
Example: `@crud.delete: false` and `@crud.subDelete: true` should not create the delete subscription.
From documentation: 
> **Note**: For subscriptions, the user needs to change the value of the respective operations to true. For example, changing subDelete to true won't work unless, delete is true.
```gql
""" 
@crud.delete: false 
"""
type Note {
id: ID!
title: String
}
```
Run `generate` with the model above. Neither a `deletedNote` subscription or a `deleteNote` mutation will be generated.
> fix: generate subscriptions when both config values are true

- packages/graphback-core/src/crud/mappingHelpers.ts
The `if` condition does not get entered entered when the action is `GraphbackOperationType.FIND`.
> fix: check both operation types

- examples/runtime-example/package.json
Without this the example was failing with `src/loadSchema.ts:2:26 - error TS7016: Could not find a
declaration file for module 'glob'`
/cc @wtrocki
> fix: add missing @types/glob in runtime examples

- packages/graphback-codegen-resolvers/src/ResolverGeneratorPlugin.ts
- packages/graphback-codegen-resolvers/src/formatters/apollo/jsResolverFormatter.ts
- packages/graphback-codegen-resolvers/src/formatters/apollo/resolverFormatter.ts
- packages/graphback-codegen-resolvers/src/formatters/apollo/tsResolverFormatter.ts
- packages/graphback-codegen-resolvers/src/output/outputResolvers.ts
Custom TypeScript resolvers did not include import typings from codegen.
1. Add a custom query in data model.
2. Generate resolvers.
3. Run `yarn graphql generate`.
3. Check custom resolvers. They should import `generated-types`.
> fix: add typings to custom resolvers

- packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
Currently, graphback generates only single `InputType` for create and update. 
This means that you can pass id to create. 
While this is not going to be issue for postgress as this value will be ignored and id will be autogenerated for mongo this needs to be managed
Before:
After:
> fix: Force remove id on create

- scripts/prepareRelease.sh
- scripts/release-procedure.adoc
- The `prepareReleash.sh` script assumes you have lerna installed globally. This changes it to use the local package.
- Change also switches from npm to yarn.
- Update release procedure documentation to instruct user to update `templates-release` branch.
> chore: use yarn in release script

- templates/ts-apollo-fullstack/.graphqlrc.yml
The `dbmigrations`extension configuration in `ts-apollo-fullstack` had the wrong indentation. It was under `graphback`, not as its own extension.
> fix: dbmigrations extension configuration indent

- templates/ts-apollo-fullstack/client/src/App.tsx
It addresses the issue #791 
The two state variables were initialized to empty strings.
> fix: initialized state variables

- templates/ts-apollo-runtime-backend/src/db.ts
- templates/ts-apollo-runtime-backend/src/runtime.ts
The runtime app was trying to load config from `graphback` config extension.
> fix: runtime was not using dbmigrations config

- packages/graphback-runtime-mongodb/src/OffixMongoDBDataProvider.ts
- Fix: `OffixMongoDBDataProvider` was returning the previous value rather than the updated value in the update query.
> fix: incorrect return value from offix monogdb data provider

- packages/graphback-cli/package.json
- packages/graphback-cli/src/components/config.ts
- packages/graphback-cli/src/components/db.ts
- packages/graphback-cli/src/templates/configTemplates.ts
- packages/graphback-cli/src/templates/resources/config/mongodb.json
- packages/graphback-cli/src/templates/resources/docker/mongodb.yml
- packages/graphback-runtime-mongodb/package.json
Addresses #757 
Updates - 
1. Added the option of MongoDB (and removed the option of sqlite3) in graphback config command 
2. Added the files mongodb.yml and mongodb.json for docker-compose of mongodb 
3. Added - Installing different runtime package based on the choice - @graphback/runtime-mongo or @graphback/runtime-knex 
Command `graphback db` failed with - 
`knex: Unknown configuration option 'client' value MongoDB. Note that it is case-sensitive, check documentation for supported values.` 
@ankitjena pointed out the reason for it.
Working on it.
> Added option for mongodb in graphback config

- docs/crud/crudruntime.md
- docs/crud/crudspec.md
- docs/crud/mapping.md
- docs/crud/relationships.md
- docs/db/datasources.md
- docs/intro/config.md
- docs/plugins/graphback-resolvers.md
- docs/releases.md
- templates/ts-apollo-fullstack/server/src/resolvers/createContext.ts
Update critical elements of the docs. 
Generally our docs needs another major refurb because datasources might change the workflow. For example there is no need to use graphback db with mongo
> fix: Remove major oudated elements from docs

- templates/ts-apollo-fullstack/client/package.json
See https://github.com/aerogear/graphback/issues/753
This change enables the build script for the fullstack client app.
> chore: enable build script

- templates/ts-apollo-fullstack/server/src/db.ts
Error in fullstack server template: 
```
TSError: ⨯ Unable to compile TypeScript:
src/graphql.ts(20,69): error TS2345: Argument of type 'import("/home/ephelan/code/aerogear/graphback/templates/ts-apollo-fullstack/node_modules/knex/types/index")<any, any[]>' is not assignable to parameter of type 'Knex<any, any[]>'.
Types of property 'raw' are incompatible.
Type 'import("/home/ephelan/code/aerogear/graphback/templates/ts-apollo-fullstack/node_modules/knex/types/index").RawBuilder<any, any>' is not assignable to type 'import("/home/ephelan/code/aerogear/graphback/node_modules/knex/types/index").RawBuilder<any, any>'.
Types of parameters 'value' and 'value' are incompatible.
```
This fixes that.
@wtrocki I believe this was fixed before, do you know why it is back?
> fix: return db as any

- packages/graphback-runtime-knex/src/PgKnexDBDataProvider.ts
- fixed a variable name that wasn't defined in the class that was causing issues with jest code coverate
> fix: undefined var name in PgKnexDBDataProvider

- packages/graphback-runtime/README.md
- packages/graphback-runtime/src/service/CRUDService.ts
- packages/graphback-runtime/src/service/subscriptionTopicMapping.ts
To incorporate AMQ cases we should be able to use different subscription topics. 
Follow up will be done in data sync starter to build up namespaced topics.
This change is not causing any side impacts. We just move things around.
Fixes https://github.com/aerogear/graphback/issues/945
> Allow to override subscription mapping

- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
When subscription are globally disabled in the `.graphqlrc` file then the generated schema will add an incomplete Subscription object to the schema:
```gql
type Subscription
```
This change checks for empty root types before adding to schema
> fix: add root types to schema only when fields exist

- packages/graphql-migrations/package.json
Jest is hardcoded in react scripts. When one of packages requires jest in dependencies react-scripts stop building. This fix resolves the issue
> chore: Move jest to dev dependencies

- packages/graphback-codegen-resolvers/src/templates/resolverWrapper.ts
The generated resolvers JavaScript file was not exporting the resolver object.
> fix(resolvers): export generated code

- docs/intro/config.md
- docs/plugins/introduction.md
- packages/graphback-cli/src/components/generate.ts
- packages/graphback-cli/src/templates/configTemplates.ts
- templates/ts-apollo-fullstack/.graphqlrc.yml
- templates/ts-apollo-runtime-backend/.graphqlrc.yml
fixes: https://github.com/aerogear/graphback/issues/977
For backwards compatibility specifying a dir like `./model` will still work as it did before, but it also means you can supply globs or arrays. For example, the following are both valid now.
```yaml
extensions:
graphback:
model: ./model/**/*.graphql
```
```yaml
extensions:
graphback:
model:
- ./model/comment.graphql
- ./model/note.graphql
```
There is also a custom [`loadSchema` function in graphql-serve](https://github.com/aerogear/graphback/blob/master/packages/graphql-serve/src/loadSchema.ts#L12-L24) which I am more than happy to update too if you think it's worth it
> fix: accept globs and array of globs for model option in config

- templates/ts-apollo-mongodb-runtime-backend/src/index.ts
- templates/ts-apollo-runtime-backend/package.json
- templates/ts-apollo-runtime-backend/src/index.ts
The Apollo PostgreSQL Runtime template is missing `@graphback/runtime-knex` which is required to create data sources and start the server.
> fix(Apollo+Postgres+Runtime): add missing dependency

- packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
When running the command `yarn test` a below deprecated warning message was printed:
```
(node:75999) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```
Let's fix the issue by adding the `useUnifiedTopology` options as suggested in the deprecation notice.
/cc @wtrocki @craicoverflow
> fix: remove deprecation warning from mongo runtime tests

- packages/graphback-core/src/plugin/GraphbackPluginEngine.ts
- packages/graphback/src/GraphbackConfig.ts
- packages/graphback/src/GraphbackGenerator.ts
- packages/graphback/src/GraphbackRuntime.ts
- packages/graphback/src/index.ts
- packages/graphback/src/loadPlugins.ts
This PR introduces some minor refactoring of the runtime and core packages, without making any changes to functionality. There are more areas that can be improved but I figured it would be nice to do things in smaller easy to digest PRs.
* GraphbackGenerator `initializePlugins` refactored into pure `loadPlugins` function. Instead of passing the plugin engine into it just to call `registerPlugin` we just return an array of initialized plugins which can then be passed into `GraphbackPluginEngine`. I've left the `registerPlugin` function just in case.
* `GraphbackRuntime` no longer extends `GraphbackGenerator`. The only reason it was doing that was to call `initializePlugins` which is not longer needed.
* `GraphbackRuntime` used to call `this.getMetaData()` in multiple places which would …
> refactor: minor changes to runtime initialization

- packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
- packages/graphback-runtime-mongodb/package.json
- packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
- packages/graphback-runtime-mongodb/src/buildQuery.ts
- packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
The mquery syntax is mostly similar to mongodb native driver queries with some sugar added, All of find, delete, update queries are still present, with the exception of a insert query. So with this, MongoDataProvider uses mquery for all operations except 'create'. I also noticed that we don't test the batchRead operation, which I also changed to use mquery, so if possible I would like to write a test for it just to be safe?
> Implement New CRUD spec for mongo

- packages/graphback-codegen-client/tests/__snapshots__/GraphQLClientCreatorTest.ts.snap
- packages/graphback-runtime-knex/src/knexQueryMapper.ts
- packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
AND/OR/NOT clauses can accept a list of filters or a single object, but was only working for list.
> fix(runtime-knex): add mapping for object clauses

- packages/graphql-migrations/src/abstract/Table.ts
- packages/graphql-migrations/src/abstract/TableColumn.ts
- packages/graphql-migrations/src/abstract/generateAbstractDatabase.ts
- packages/graphql-migrations/src/diff/Operation.ts
- packages/graphql-migrations/src/util/comments.ts
- packages/graphql-migrations/src/util/getIndexes.ts
- packages/graphql-migrations/src/util/transformDefaultValue.ts
graphql-migrations generates a slightly different abstract database when comparing the existing database to the schema. One sets defaultValue on columns to undefined, and the other uses null. Because of this it is repeating the same migration operations every time.
Run graphql-migrations on an already up to date database. The number of operations should be 0.
> fix: set default value as undefined instead of null

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-runtime-knex/src/knexQueryMapper.ts
- packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
- packages/graphback-runtime/src/service/CRUDService.ts
- There was an issue when nested and/or/not operators - it only worked one level deep - this fixes that.
- Add ability to perform filtering by checking if a field is null/non-null
- This also adds ability to filter between ranges.
To filter results on a null field:
```graphql
query findNotes {
findNotes(filter: {items:{eq:null}}) {
items {
id
title
items
}
}
}
```
To perform nested operator filtering (or -> not):
```graphql
query findNotes {
findNotes(filter: {items:{eq:null}, or:{not:{id:{eq:null}}}}) {
items {
id
title
items
}
}
}
```
> fix: add ability to nest or/not queries

- commitlint.config.js
- package.json
We are using conventional commits but not strict about it and typos can sneak in. I want us to enforce it so that we can eventually generated changelogs from commits
https://www.conventionalcommits.org/en/v1.0.0/
> Add husky and commitlint to ensure commits follow conventional commit

- packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
- packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
- templates/ts-react-apollo-client/src/generated-types.tsx
Fixing small issues with mongodb querying
1. Run mongodb template
2. Execute queries in order
```graphql
mutation create {
createNote(input: { id: "", title: "test", description: "" }) {
id
title
}
}
query getNote {
getNote(id: "5ec65b464edd042b5c862286") {
id
}
}
query query2 {
findNotes(
filter: { description: {eq:"" } }
page: { offset: 0, limit: 40 }
orderBy: { field: "title", order: ASC }
) {
items {
id
title
description
}
}
}
```
> fix: getX queries for mongo and pagination

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-codegen-schema/tests/mock.graphql
- packages/graphback-core/src/crud/mappingHelpers.ts
When a model contained an enum, an error `Error: ThunkComposer() returns empty value: undefined` was
thrown, which stopped the server from being started. Let's fix this by allowing enums to be
recognisable as filter input types.
Fixes #1299
> fix: runtime schema generation when model contains an enum

- docs/crud/crudspec.md
- website/src/components/Video/index.jsx
Added [Graphback - In a Nutshell](https://youtu.be/z3hUF5egjT4) to graphback.dev. homepage.
This is from a recent online presentation.
Also, this PR fixes an issue in docs where Markdown was preceiving `<>` as a HTML tag and was failing to build.
> Add new video demo to website

- scripts/validateRelease.sh
Reverts aerogear/graphback#1308
This actually caused issue when releasing https://github.com/aerogear/graphback/releases/tag/0.14.0-alpha1 
as the output contained more than the packages under lerna. 
When releasing CI failed with 
```
#!/bin/bash -eo pipefail
TAG=$CIRCLE_TAG npm run release:validate
> graphback-monorepository@1.0.0 release:validate /home/circleci/aerogear/graphback
> ./scripts/validateRelease.sh
package yarn has version un but expected 0.14.0-alpha1
```
More logs here https://circleci.com/gh/aerogear/graphback/4421?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
The failure was due to the command `yarn lerna --loglevel=silent ls | awk -F ' ' ' ' '{print $1}` outputting 
something like 
```
yarn $ graphback-cli @graphback/codegen-client …
```
> Revert "chore: use locally installed lerna instead of a global one"

- README.md
Let's align the badges with the minimum version required version - https://github.com/aerogear/graphback/blob/8e84840aa22d9783adfda6684ec8019fccfc016c/packages/graphback/package.json#L19
> chore: update NodeJs version to 10.15.3 in Readme file

- packages/graphback/src/GraphbackRuntime.ts
The pubUpdate and pubDelete configuration were mixed up causing issues in subscriptions not being
fired up
Fixes #1351
> fix: subscription configuration mixup

- packages/graphback-runtime-mongodb/src/queryBuilder.ts
The mongodb query builder was not using the 'in' operator, this PR fixes that
> Fix query builder not using 'in' operator

- packages/graphback-core/src/db/getPrimaryKey.ts
- packages/graphback-core/tests/getPrimaryKeyTest.ts
If the model contains a primary key field with `@db` annotation and an id scalar field, the computed
primary key will be different depending on the order of declaration. Fix the issue by making sure
that a primary key with `@db` is of high priority while defaulting to an id scalar field.
Fixes https://github.com/aerogear/graphback/issues/1401
> fix(core): getPrimaryKey is undeterministic

- packages/graphql-migrations/src/util/getCheckConstraints.ts
When checking constraints in postgres 12, the sql query belowed failed
with `column c.consrc does not exist`
```
select
c.conname as "indexName",
array_to_string(array_agg(a.attname), ',') as "columnNames",
c.consrc as "expression"
from
pg_class t,
pg_constraint c,
pg_namespace n,
pg_attribute a
where
c.conrelid = t.oid
and n.oid = c.connamespace
and a.attrelid = t.oid
and a.attnum = ANY(c.conkey)
and c.contype = 'c'
and t.relname = ?
and n.nspname = ?
group by
t.relname,
c.conname,
c.consrc;
```
This was because the `consrc` column was removed from the `pg_constraint` table starting from pg 12.
Starting the version 11, https://www.postgresql.org/docs/11/catalog-pg-constraint.html, it is recommended to use pg_get_constraintdef()
to extract the definition of a check constraint.
Fixes …
> fix: postgres 12 issue when running migrations multiple times

- docs/intro/datamodel.md
- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-codegen-schema/tests/mock.graphql
- packages/graphql-migrations/src/abstract/generateAbstractDatabase.ts
Adding a field with custom type was breaking since the custom type is neither a scalar , enum or a
model type so we cannot really generate the necessary crud bits for it. Let's ignore the field with
undefined type as it is breaking the CRUD bits generation part. `undefined` is returned by this
method
https://github.com/aerogear/graphback/blob/ae5c6d5148877fb7ce6fa622036dcd31ad6b9946/packages/graphback-core/src/crud/mappingHelpers.ts#L159-L173
Fixes https://github.com/aerogear/graphback/issues/1432
> fix(codegen-schema): can't add field with custom type to model type

- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
Noticed that master build is broken cause of https://github.com/aerogear/graphback/pull/1457 but the PR did not have latest changes from master hence the snapshot issue.
> test(codegen-schema): update snapshot to make test pass

- packages/graphql-serve/src/GraphbackServer.ts
This fixes a bug in `graphql-serve@0.14.0-alpha6`
```
❯ gqls serve .                         
No port number specified.
Starting server on random available port...
(node:307354) UnhandledPromiseRejectionWarning: TypeError: get_port_1.default is not a function
at GraphbackServer.<anonymous> (/home/ephelan/code/aerogear/graphback/packages/graphql-serve/dist/GraphbackServer.js:31:52)
at Generator.next (<anonymous>)
```
> fix(graphql-serve): TypeError: get_port_1.default is not a function

- docs/plugins/graphback-schema.md
- docs/releases.md
- integration/.graphqlrc.yml
- integration/.vscode/launch.json
- integration/tests/runtime-workflow.ts
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts
- packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
- packages/graphback-runtime-mongodb/tests/__util__.ts
Fixes #1512 
This change allows the specifying of the schema in a single config option, `outputPath`:
```ts
const schemaPlugin = new SchemaCRUDPlugin({
outputPath: './path/to/my/schema.js'
});
```
You can still let graphback create a default file type with:
```ts
const schemaPlugin = new SchemaCRUDPlugin({
outputPath: './path/to/schema'
});
```
This creates `/path/to/schema/schema.graphql`
This is a breaking change because it removed the `format` and `outputFileName` options.
> feat: allow specifying of file name in outputPath option

- packages/graphback-datasync/package.json
required by https://github.com/aerogear/graphback/blob/f95b40e611c46b8e10b61f6ae771aa15833a0cce/packages/graphback-datasync/src/DataSyncPlugin.ts#L3
> chore: make codegen-schema as prod deps in datasync plugin

- packages/graphback-cli/src/config/graphbackExtension.ts
- packages/graphback-cli/src/index.ts
Fixes #1530 
`graphback-cli` exported all code from the `generate` command, which requires `graphql`.
This meant that the CLI would not work from any directory which is required for `init`.
To verify, run this command from a folder outside of Graphback (eg: $HOME)
Run `node <path/to/graphback>/packages/graphback-cli/dist/index.js init test`
It should work.
> fix(cli): Cannot find module 'graphql'

- packages/graphback-core/src/runtime/GraphbackProxyService.ts
- packages/graphback-core/src/runtime/index.ts
- packages/graphback-keycloak-authz/src/KeycloakCrudService.ts
Idea here is to simplify creation of the service chains even further. 
Currently you need to creat entire class witch is very verbose. 
Adding proxy service to the core and extending it is very simple and can be reused to build long chain of services without implementing entire API
> feat: add proxy service for simplicity of extending service chain

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-core/package.json
- packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts
- packages/graphback/tests/buildGraphbackAPITest.ts
Fixes #1546 #1556 
Returns resolvers as an object instead of an array.
> fix(core): return resolvers as object

- packages/graphback/src/loadPlugins.ts
Let's do so since plugins can also be defined programmatically.
Fixes https://github.com/aerogear/graphback/issues/1296
> fix(plugin): make plugins optional in config

- packages/graphql-serve/package.json
- packages/graphql-serve/src/GraphbackServer.ts
- packages/graphql-serve/src/commands/serve.ts
- packages/graphql-serve/src/components/serveHandler.ts
- packages/graphql-serve/src/runtime.ts
Motivation here is to enable datasync in graphql serve.
We need that to have headless backend for offix that works with conflicts etc. 
This will be only for example purposes but it will be really powerful for the demos.
1. Link cli
2. Run graphql-serve serve task.graphql -p 8080 --datasync
> enable datasync for graphql-serve

- docs/releases.md
- integration/mock.graphql
- integration/tests/__snapshots__/runtime-workflow-postgres.ts.snap
- integration/tests/runtime-workflow-mongo.ts
- integration/tests/runtime-workflow-postgres.ts
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-codegen-schema/src/definitions/copyWrappingType.ts
- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-codegen-schema/tests/copyWrappingTypeTest.ts
- packages/graphback-core/package.json
- packages/graphback-core/src/crud/mappingHelpers.ts
- packages/graphback-core/src/db/dataMapper.ts
- packages/graphback-core/src/index.ts
- packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts
- packages/graphback-core/src/plugin/ModelDefinition.ts
- packages/graphback-core/src/plugin/getSelectedFieldsFromResolverInfo.ts
- packages/graphback-core/src/scalars/index.ts
- packages/graphback-core/src/scalars/scalars.ts
- packages/graphback-runtime-knex/src/knexQueryMapper.ts
- packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
- packages/graphql-migrations/src/abstract/generateAbstractDatabase.ts
- templates/ts-apollo-postgres-backend/model/datamodel.graphql
This adds support for create/update of embedded relationship documents in both PostgreSQL and MongoDB.
Before this change, it was not possible to CREATE/UPDATE/FIND fields which are GraphQL types which are not models because:
a) There were no input fields added for these types to the CRUD input types
b) `getSelectedFieldsFromResolverInfo` did not include GraphQL type fields in the selectable fields, so `.select(x)` would never return this data from the database.
TL;DR we added support for non-model type fields in out models in https://github.com/aerogear/graphback/issues/1432 but this data could not be inserted/updated/retrieved from the database.
```graphql
"""
@model
"""
type Note {
id: ID!
title: String
"""
this annotation is only needed for Postgres
@db(type: 'json') 
"""
comments: …
```
> feat: support create/update of embedded JSON objects

- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
- packages/graphql-serve/tests/__snapshots__/printSchema.test.ts.snap
Closes #1592 
This PR makes return types for mutations nullable.
Implements change to GraphQLCRUD spec https://github.com/graphqlcrud/spec/pull/22
> fix(schema): make return types nullable

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
- packages/graphql-serve/tests/__snapshots__/printSchema.test.ts.snap
This change makes filter field lists `and` and `or` non-nullable
```
and: [CommentFilter!]
or: [CommentFilter!]
```
Implements https://github.com/graphqlcrud/spec/pull/26
> fix(schema): make AND/OR fields non-nullable

- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback/tests/buildGraphbackAPITest.ts
Fixes #1427 
This allows the server to start if there are no types annotated by `@model`.
To verify, start a server with this model:
```
type User {
name: String
}
type Query {
hello: String
}
```
> fix: start server if schema has no models

- packages/graphback-keycloak-authz/src/KeycloakCrudService.ts
I removed batching config and ended up with issues. Forgot to have extra check on the array.
Cannot read property 'noteId' of undefined"
> fix: batch method when keycloak config is not suppied

- docs/graphqlserve/graphqlserve.md
Add a link to the CRUD overview from graphql-serve
> docs(graphql-serve): add link to CRUD section

- docs/databases/migrations.md
- docs/graphql-migrations/api-reference.md
- docs/graphql-migrations/db-design.md
- docs/graphql-migrations/filter.md
- docs/graphql-migrations/intro.md
- docs/graphql-migrations/plugins.md
- website/sidebars.json
> docs(website): add database migrations documentation

- packages/graphql-migrations/src/plugin/MigrateOperationFilter.ts
- packages/graphql-migrations/tests/removeNonSafeOperationsFilterTest.ts
Fixes https://github.com/aerogear/graphback/issues/1673
Hoping to bring this in since the `removeNonSafeOperationsFilter` will be documented / advertised here https://github.com/aerogear/graphback/pull/1674
> fix(graphql-migrations): add column.drop as unsafe operations and filter it out

- docs/crud/introduction.md
Resolves #1656 
This adds a warning to the documentation about Graphback CRUD queries overwriting custom queries that have the same name.
> docs(crud): add warning message about overriding custom queries

- CONTRIBUTING.md
- docs/.old/db/datasources.md
- docs/.old/intro/graphqlserve.md
- docs/.old/intro/quickstart.md
- docs/.old/releases.md
- docs/databases/mongodb.md
- docs/getting-started/adding-graphback-to-your-project.md
- docs/getting-started/creating-a-new-application.md
- docs/graphql-migrations/intro.md
- docs/graphqlserve/graphqlserve.md
- packages/graphql-serve/README.md
- templates/ts-apollo-postgres-backend/.graphqlrc.yaml
- templates/ts-react-apollo-client/README.md
- website/README.md
- website/versioned_docs/version-0.10.x/database-schema-migrations.md
- website/versioned_docs/version-0.11.x/db/datasources.md
- website/versioned_docs/version-0.11.x/db/migrations.md
- website/versioned_docs/version-0.11.x/intro/graphqlserve.md
- website/versioned_docs/version-0.11.x/intro/quickstart.md
- website/versioned_docs/version-0.12.x/db/datasources.md
- website/versioned_docs/version-0.12.x/db/migrations.md
- website/versioned_docs/version-0.12.x/intro/graphqlserve.md
- website/versioned_docs/version-0.12.x/intro/quickstart.md
- website/versioned_docs/version-0.9.x/commands.md
- website/versioned_docs/version-0.9.x/database-schema-migrations.md
Replace `sh` with `bash` everywhere for better syntax highlighting in Docusaurus.
> chore: replace sh with bash for syntax highlighting

- docs/releases.md
- integration/tests/runtime-workflow-mongo.ts
- integration/tests/runtime-workflow-postgres.ts
- packages/graphback-codegen-client/src/ClientCRUDPlugin.ts
- packages/graphback-codegen-client/src/helpers/writeDocuments.ts
- packages/graphback-codegen-client/tests/GraphQLClientCreatorTest.ts
- packages/graphback-codegen-client/tests/__snapshots__/GraphQLClientCreatorTest.ts.snap
This removes the `format` configuration from ClientCRUDPlugin as it is preferred to infer the file extension through the `outputFile` config.
> feat(clientcrudplugin): remove the format config option

- packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
Also mention the recommended usage of SQLiteKnexDBDataProvider for SQLite database.
> refactor(runtime-knex): update comments to not use deleted PgKnexDBDataProvider

- docs/databases/mongodb.md
- docs/databases/postgres.md
- docs/databases/sqlite.md
- packages/graphback-runtime-knex/src/index.ts
Also exposes `SQLiteKnexDBDataProvider` as public API as it can be used
for testing / development purposes.
> docs(website): add sqlite database documentation

- renovate.json
We want to avoid any code changes at this point including bumps.
Disabling this temporairly so we can lock dependencies and do proper line of testing
> chore: disable automerge

- packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
- packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
Seems like we were missing a test for "not in" filter, lets add a few
for the Mongo and Knex providers.
Test added as verification of https://github.com/aerogear/graphback/issues/1495
> test(data-providers): add test for "not in" filters

- packages/graphback-core/src/plugin/GraphbackPluginEngine.ts
Instead have a dedicated "GraphbackPluginEngine#createResolvers" method which is called after schema
transfromation phase has finished.
Fixes https://github.com/aerogear/graphback/issues/1742
> refactor(plugin-engine): do not create resolvers in the "GraphbackPluginEngine#createSchema" method

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts
Fixes #1751 
The original reason we disabled model fields on non-model types was because of circular generation causing a Maximum call stack size exceeded error, in scenarios where a Model referenced a non-model which referenced the model again.
Obviously we made this too restrictive and prevented other common use cases.
Start your Graphback server with the following model:
```gql
type AnonymousJWTAuthResult {
user: User!
csrfToken: String!
authJWT: String!
}
"""@model"""
type User {
id: ID!
name: String
}
type Query {
test: AnonymousJWTAuthResult
}
```
> fix(schema): allow model field on non-model types

- docs/crud/subscriptions.md
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-core/src/runtime/CRUDService.ts
- packages/graphback-core/src/runtime/index.ts
- packages/graphback-core/src/runtime/withSubscriptionFilter.ts
- packages/graphback-runtime-knex/tests/service/DefaultCRUDServiceTest.ts
This PR implements simplistic in-memory filtering of subscriptions using [withFilter](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#subscription-filters) from graphql-subscriptions.
Set up a subscription with a filter:
```gql
subscription {
newNote(filter: {title:"note1", description:"note1hello"}) {
id
title
description
comments {
id
}
}
}
```
Create a mutation matching the filter params. You should get a subscription even. Now try it with different filters.
```gql
mutation {
createNote(input: {
title: "note1",
description:"note1hello"
}) {
id
}
}
```
Opening this PR up for feedback now for a conversation on the general implementation. Tried adding quick tests to help with verify but they are non-trivial tricky so can revisit this.
> feat: in memory subscription filtering

- website/docusaurus.config.js
- website/package.json
This fix an issue when launching `yarn start` or `yarn build` as the commands
errored with the following message below:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:120:11)
at Object.resolve (path.js:980:7)
at pluginContentBlog (/xxxx/graphback/website/node_modules/@docusaurus/plugin-content-blog/lib/index.js:28:40)
```
> chore: update docusaurus version to latest alpha release

- templates/ts-apollo-mongodb-datasync-backend/package.json
This updates the version of graphql in the datasync template to use v15.x.
Was there a reason this template still used v14.x?
Since this is a different major version to the one used in Graphback devDependencies, I was unable to start the datasync template when using the one directly in the repo.
However this is not an issue in production, it is more of a developer experience issue.
> chore: update graphql version to v15.3.0

- renovate.json
This reverts commit fefa6f83c65acf2651459b2a028d28f3bbc9ad67.
Re-enable auto-merging of dependencies with minor and patch releases.
> revert: chore: disable automerge

- .vscode/launch.json
- templates/ts-apollo-mongodb-backend/.env
- templates/ts-apollo-mongodb-backend/docker-compose.yml
- templates/ts-apollo-mongodb-datasync-backend/.env
- templates/ts-apollo-mongodb-datasync-backend/docker-compose.yml
The Docker Compose files were mapping to the local port 27017 (the default MongoDB port)
This should be reserved for MongoDB as it is highly possible that the developer might have MongoDB running.
We already map the Postgres containers to a different port (55432).
> chore(templates): map Mongo container to port 27018

- docs/authentication/keycloak.md
0.16.0 will officially announce keycloak - I will drop follow up blog post.
> fix: remove note about alpha for keycloak for 0.16.0 release

- packages/graphback-codegen-schema/package.json
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
This removes the number of queries issued to the database
Fixes https://github.com/aerogear/graphback/issues/1304
Go to current [master](https://github.com/aerogear/graphback/commit/9e71c786e429984046a7f6dba022b0effd760ef6) and use the PostgresSQL template with the following model:
```graphql
""" @model """
type Note {
id: ID!
title: String!
"""
@oneToMany(field: 'note')
"""
comments: [Comment!]!
}
""" @model """
type Comment {
id: ID!
text: String
note: Note!
}
```
```shell
DEBUG=knex:query yarn develop
```
create a note which has three comments linked to it. 
If I issue a graphql query to retrieves *Notes* like below
```graphql
query {
findNotes {
items {
id
comments {
id
}
}
}
}
```
I am seeing only two db queries below thanks to dataloader, this is fine.
```log
querying object Note …
```
> perf: use dataloader to resolve oneToOne or manyToOne relationships

- packages/graphback-core/src/db/dataMapper.ts
- packages/graphback-core/tests/dataMapperTest.ts
- packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
A null value type is an object, this was the transformed to "null" by
the fixed logic resulting in errors for non string columns in database.
Fixes https://github.com/aerogear/graphback/issues/1837
> fix(core): avoid stringfying "null" values as `"null"`

- integration/tests/runtime-workflow-datasync-conflicts.ts
- packages/graphback-datasync/package.json
- packages/graphback-datasync/src/DataSyncPlugin.ts
- packages/graphback-datasync/src/deltaHelper.ts
- packages/graphback-datasync/src/deltaSource.ts
- packages/graphback-datasync/src/helpers/createDataSync.ts
- packages/graphback-datasync/src/index.ts
- packages/graphback-datasync/src/providers/DataSyncConflictProvider.ts
- packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
- packages/graphback-datasync/src/providers/createDataSyncMongoDbProvider.ts
- packages/graphback-datasync/src/providers/index.ts
- packages/graphback-datasync/src/services/createDataSyncService.ts
- packages/graphback-datasync/src/util.ts
- packages/graphback-datasync/tests/DataSyncConflictProviderTest.ts
- packages/graphback-datasync/tests/DataSyncPluginTest.ts
- packages/graphback-datasync/tests/__snapshots__/DataSyncPluginTest.ts.snap
- templates/ts-apollo-mongodb-datasync-backend/src/index.ts
Rather hopeful about this one :crossed_fingers: 
```typescript
const { typeDefs, resolvers, contextCreator } = createDataSync(modelDefs, db, { Comment: { enabled: true, conflictResolution: serverSideConflictResolution }});
```
> feat(datasync): add conflicts by version

- integration/postgres-model.graphql
- integration/tests/__snapshots__/runtime-workflow-postgres.ts.snap
- integration/tests/runtime-workflow-postgres.ts
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-core/src/runtime/CRUDService.ts
This makes sure that relationships are loaded within unique context thus avoid resolving fields in
different context results than the one it was requested
Fixes https://github.com/aerogear/graphback/issues/1876
- Run the added integration test without the change in the codebase should err. (simply pulling these changes and running the test should be enough). 
- Then build the patch and run the tests again  `yarn build && yarn test:integration -u`
> fix: make sure dataloader name is unique enough

- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
- packages/graphback-codegen-schema/tests/mock.graphql
- packages/graphback-core/package.json
- packages/graphback-core/src/runtime/QueryFilter.ts
- packages/graphback-core/src/runtime/createInMemoryFilterPredicate.ts
- packages/graphback-core/src/scalars/index.ts
- packages/graphback-core/src/utils/convertType.ts
- packages/graphback-core/tests/createInMemoryFilterPredicateTest.ts
- packages/graphback-runtime-knex/package.json
Closes #1864 
This PR does:
- Add Graphback scalars to the `QueryFilter` and the and/or/not operators
- Removes generation of filter inputs for unknown custom scalars.
> Update QueryFilter type with Graphback scalars and disable generation of filters for unknown custom scalars.

- docs/datasync/conflict-resolution-intro.md
- docs/datasync/delta-queries.md
- packages/graphback-datasync/src/providers/DataSyncConflictProvider.ts
- packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
- packages/graphback-datasync/tests/DataSyncConflictProviderTest.ts
- packages/graphback-datasync/tests/DataSyncMongoDBTests.ts
Some minor fixes for DataSync as well as updated docs for TTL
Fixes #1890
> Datasync minor fixes

- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
Closes #1898 
When writing the example in [Create your own Graphback plugin](https://graphback.dev/docs/next/plugins/create) example I noticed that this was done incorrectly in the SchemaCRUDPlugin. Everything still works the exact same as before.
> refactor(codegen-schema): case to IObjectTypeResolver instead if IFieldResolver

- docs/graphqlserve/graphqlserve.md
- packages/graphback-datasync/src/util.ts
- packages/graphql-serve/src/GraphbackServer.ts
- packages/graphql-serve/src/commands/serve.ts
- packages/graphql-serve/src/components/serveHandler.ts
- packages/graphql-serve/src/runtime.ts
This PR adds conflicts to --datasync option of graphql serve with default strategy of clientsidewins which can be overridden by the --conflict=client or --conflict=server option
> feat(graphqlserve): add conflicts to --datasync

- docs/releases.md
- packages/graphback-runtime-knex/package.json
- packages/graphql-migrations/package.json
Resolves #1640
To verify, you will want a template outside of this monorepo.
Install Graphback to the project like so:
```
"dependencies": {
"@graphback/runtime-knex": "/home/username/code/aerogear/graphback/packages/graphback-runtime-knex"
}
```
Now, you can change your Knex version to anything in 0.20.x || 0.21.x and your application will run and you can perform database calls.
> Install knex as a peer dependency

- integration/tests/runtime-workflow-datasync-conflicts.ts
- integration/tests/runtime-workflow-datasync.ts
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts
- packages/graphback-core/src/plugin/ModelDefinition.ts
- packages/graphback-core/src/plugin/getSelectedFieldsFromResolverInfo.ts
- packages/graphback-datasync/src/DataSyncPlugin.ts
- packages/graphback-datasync/src/helpers/createDataSync.ts
- packages/graphback-datasync/src/providers/createDataSyncMongoDbProvider.ts
- packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
Following
https://github.com/aerogear/graphback/issues/1675#issuecomment-658743262
and https://github.com/aerogear/graphback/issues/1728#issuecomment-658741379
Also use this information to improve the selectedFields retrieval logic as suggested in
https://github.com/aerogear/graphback/pull/1729#discussion_r455017887
> parse fields info into ModelDefinition

- integration/mongodb-model.graphql
- integration/postgres-model.graphql
- integration/tests/runtime-workflow-mongo.ts
- integration/tests/runtime-workflow-postgres.ts
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
When the parent object contains the relationship field, it is more interesting to resolve it
directly without hitting the database. This gives user an ability to write custom resolvers that
fetch full dataset in whatever way they wish e.g via join statements and having that data returned
directly without querying again the database to resolve relationship field
Resolves https://github.com/aerogear/graphback/issues/1925
> feat(resolvers): allow resolving relationship field directly without hitting the database

- performance/package.json
The package was published as https://www.npmjs.com/package/graphback-benchmarks, let's make it
private to avoid such cases.
> chore: make the benchmark package private to avoid publishing it

- integration/tests/runtime-workflow-mongo.ts
- integration/tests/runtime-workflow-postgres.ts
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
Improve the condition that checked if parent object has the relationship resolved. This also take
care of when the relationship field is "undefined" or "null". With the previous check, we'll query
the database again which seemed wrong. I've added a some data values in the previous tests.
Related to https://github.com/aerogear/graphback/pull/1933 and
https://github.com/aerogear/graphback/pull/1925
> fix(schema-plugin): make sure that "null"/"undefined" relationship values are considered resolved

- docs/plugins/creating-your-own-plugin.md
- docs/releases.md
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-core/src/runtime/interfaces.ts
- packages/graphback-datasync/src/DataSyncPlugin.ts
- packages/graphback-keycloak-authz/tests/KeycloakCrudService.test.ts
- packages/graphback/src/buildGraphbackAPI.ts
The `graphback` property has been removed from `GraphbackContext`.
```patch
export interface GraphbackContext {
-  graphback: {
-    services: GraphbackServiceConfigMap
-  }
+  graphback: GraphbackServiceConfigMap
}
```
Now you can reach the Graphback services like so: 
```patch
- context.graphback.services.Note.findBy(...);
+ context.graphback.Note.findBy(...);
```
This is another enabler PR for #1637
> feat(context): move service map to context top-level

- integration/package.json
- templates/ts-apollo-mongodb-backend/model/datamodel.graphql
- templates/ts-apollo-mongodb-backend/src/customContext.ts
- templates/ts-apollo-mongodb-backend/src/generated-types.ts
- templates/ts-apollo-mongodb-backend/src/index.ts
- templates/ts-apollo-mongodb-backend/src/resolvers/noteResolvers.ts
- templates/ts-apollo-mongodb-backend/src/schema/schema.graphql
- templates/ts-apollo-mongodb-datasync-backend/model/datamodel.graphql
- templates/ts-apollo-mongodb-datasync-backend/src/customContext.ts
- templates/ts-apollo-mongodb-datasync-backend/src/generated-types.ts
- templates/ts-apollo-mongodb-datasync-backend/src/index.ts
- templates/ts-apollo-mongodb-datasync-backend/src/resolvers/noteResolvers.ts
- templates/ts-apollo-mongodb-datasync-backend/src/schema/schema.graphql
- templates/ts-apollo-postgres-backend/model/datamodel.graphql
- templates/ts-apollo-postgres-backend/src/customContext.ts
- templates/ts-apollo-postgres-backend/src/generated-types.ts
- templates/ts-apollo-postgres-backend/src/index.ts
- templates/ts-apollo-postgres-backend/src/resolvers/noteResolvers.ts
- templates/ts-apollo-postgres-backend/src/schema/schema.graphql
- templates/ts-react-apollo-client/codegen.yml
- templates/ts-react-apollo-client/package.json
- templates/ts-react-apollo-client/src/App.tsx
- templates/ts-react-apollo-client/src/components/notes/CreateNote.tsx
- templates/ts-react-apollo-client/src/components/notes/OneNote.tsx
- templates/ts-react-apollo-client/src/generated-types.tsx
- templates/ts-react-apollo-client/src/graphql/getDraftNotes.graphql
- templates/ts-react-apollo-client/src/index.tsx
**DRAFT**
This PR adds a custom resolver to the Postgres Backend template.
Opening this as a draft so you can see if this is a good approach. It is pretty much as was discussed in  https://github.com/aerogear/graphback/issues/1637
Once we have agreement I can follow up and add this to the other templates.
> chore(templates): add example custom resolver

- docs/resolvers/custom-resolvers.md
- website/sidebars.json
This PR adds documentation for how you can use the Graphback services in your own custom resolvers.
> docs: add custom resolvers page

- templates/ts-apollo-postgres-backend/package.json
The postgres template requires the pg dependency
> fix(deps): add missing pg dependency

- packages/graphql-serve/package.json
Without this I was running through
```log
error TS2307: Cannot find module 'graphql-serve' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
> fix: correct main path of graphql-serve

- .github/workflows/build-website.yml
- .github/workflows/graphback-ci.yml
Make the timeout to 60 minutes to fail fast instead of the default 360 which is kinda long.
> ci: add timeout in minutes

- packages/graphql-serve/src/commands/printSchema.ts
This fixes #1999 - the full chalk module needed to be imported.
> fix(graphql-serve): import full chalk module

- packages/create-graphback/src/index.ts
- packages/create-graphback/src/init/components.ts
Fixes https://github.com/aerogear/graphback/issues/1981
To verify:
1. checkout the PR locally
2. Build the project
3. Use the following command to launch the init script:
```
node packages/create-graphback/dist/index.js test --filter mongo
```
This will only display mongo related templates.
Filtering is optional, a full list will be displayed if this option is
not supplied.
> feat(create-graphback): add a filter option to filter limit displayed templates

- packages/graphql-serve/src/commands/printSchema.ts
The command was broken cause of the wrong import statement.
This caused an `undefined` error.
To verify:
Build the current master and launch the print schema command:
```bash
cd packages/graphql-serve/dist/
node index.js print-schema templates/ts-apollo-mongodb-datasync-backend/model/datamodel.graphql
```
Apply the patch, build and re-launch the command.
> fix(graphql-serve): print-schema command was not working

- docs/releases.md
- packages/graphback-core/src/runtime/QueryFilter.ts
- packages/graphback-core/src/runtime/createInMemoryFilterPredicate.ts
- packages/graphback-core/tests/createInMemoryFilterPredicateTest.ts
- packages/graphback-runtime-knex/src/KnexDBDataProvider.ts
- packages/graphback-runtime-knex/src/knexQueryMapper.ts
- packages/graphback-runtime-knex/tests/data/KnexDbDataProviderTest.ts
- packages/graphback-runtime-knex/tests/knexQueryMapperTest.ts
- packages/graphback-runtime-mongodb/src/queryBuilder.ts
- packages/graphback-runtime-mongodb/tests/MongoDataProviderTest.ts
- packages/graphback-runtime-mongodb/tests/queryBuilderTest.ts
This PR completely rewrites the Knex query builder, which was only ever intended as a prototype version originally and was very hard to maintain.
> refactor(knex): refactor knex query builder and fixes an issue where or queries were not mapped correctly

- packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts
The `$in` key should really be `in`, because the type is QueryFilter which does not have any `$in` property - this is not getting picked because the default generic is `any`.
> fix: change wrong filter key

- docs/cli/graphback-cli.md
- packages/graphback-cli/README.md
- website/versioned_docs/version-0.14.x/cli/graphback-cli.md
- website/versioned_docs/version-0.15.x/cli/graphback-cli.md
- website/versioned_docs/version-0.16.x/cli/graphback-cli.md
Fixes https://github.com/aerogear/graphback/issues/1954
PS: The issue was a good first issue and tagged for Hacktoberfest but I thought we could bring this early on since https://graphback.dev/docs/cli/graphback-cli looks weird.
> docs(graphback-cli): add generate command documentation

- integration/package.json
- integration/tests/graphql-migrations-postgres.ts
- packages/graphql-migrations/src/connector/read.ts
- packages/graphql-migrations/src/diff/computeDiff.ts
- packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts
Fixes #2047 
Could not add a unit test for this because it is only a Postgres issue - we do need to think about integration tests for this scenario but due to it being a blocker we should get it merged and release first.
> fix(graphql-migrations): migration failed for auto increments column

- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback/tests/buildGraphbackAPITest.ts
Fixes #2070 
1. Disable all subscriptions, either globally through `buildGraphbackAPI` or per model in the `@model` annotation.
Start the server - it should work. Debug the `resolvers` object created by Graphback, there should be no Subscription resolver object.
> fix(schema): don't create empty resolver objects

- docs/releases.md
- packages/graphback/src/loadPlugins.ts
I have noticed that https://github.com/aerogear/graphback/blob/package-override/docs/plugins/creating-your-own-plugin.md no longer has information about config as well.
> feat: add ability to perform package override in config

- .eslintrc.json
- package.json
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-core/src/runtime/GraphbackDataProvider.ts
- packages/graphback-datasync/src/providers/DataSyncProvider.ts
- packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts
- packages/graphback-keycloak-authz/src/KeycloakConfig.ts
- packages/graphback-keycloak-authz/src/createKeycloakCRUDService.ts
- packages/graphback-runtime-knex/src/SQLiteKnexDBDataProvider.ts
- packages/graphql-migrations/src/util/getCheckConstraints.ts
- packages/graphql-migrations/src/util/getColumnComments.ts
- packages/graphql-migrations/src/util/getForeignKeys.ts
- packages/graphql-migrations/src/util/getObjectTypeFromList.ts
- packages/graphql-migrations/src/util/getPrimaryKey.ts
- packages/graphql-migrations/src/util/getTypeAlias.ts
- packages/graphql-migrations/src/util/getUniques.ts
- packages/graphql-migrations/src/util/listTables.ts
- [d4975afb0db25f9bddddee92ba0be4540133320b] removes all unused imports, and adds an ESLint rule to warn if it happens again, this will make it easier to identify and remove unused imports in the future.
- [4a00e907a62d3fc36dcb6fdbe5de2c123f09e386] disable `prefer-named-exports` rule for certain cases. Now there are no lint warnings in the repo, since there were always these few hanging around we often ignored them and might miss other new ones.
> style: remove unused imports

- docs/releases.md
- packages/graphback-core/src/runtime/CRUDService.ts
- packages/graphback-runtime-knex/src/knexQueryMapper.ts
- packages/graphback-runtime-knex/tests/knexQueryMapperTest.ts
- packages/graphback-runtime-knex/tests/service/DefaultCRUDServiceTest.ts
- 5143fb6c6a76d20f44b3e79ab25c6922408dd54a - `TypeError: Cannot read property 'page' of undefined` error is thrown when no `findBy#args` argument is null or undefined.
- d10e918 fixes an error where it was not possible to perform a `where x is/not null` query in the Knex data provider. This is already possible in the Mongo Data Provider.
All fixes accompanied by a unit test
> Fixes in CRUDService and Knex Query Mapper

- packages/graphback-core/package.json
- templates/ts-apollo-mongodb-backend/package.json
- templates/ts-apollo-mongodb-datasync-backend/package.json
- templates/ts-apollo-postgres-backend/package.json
- [`81f9612` (#2104)](https://github.com/aerogear/graphback/pull/2104/commits/81f96128e3daa27a2345070ab961b0df01c1d102) fixes an issue in the templates where path to `dist/index.js` was wrong in the `start` script.
- [`e9f6460` (#2104)](https://github.com/aerogear/graphback/pull/2104/commits/e9f6460035f676e03445a99a4d36500984a9e083) fixes https://github.com/aerogear/graphback/issues/2103.
> Fix script path to compiled `index.js` in templates and move `@types/bson` from devDependencies in `@graphback/core`

- docs/authentication/keycloak.md
- docs/releases.md
- packages/graphback-keycloak-authz/src/KeycloakCrudService.ts
- packages/graphback-keycloak-authz/tests/KeycloakCrudService.test.ts
Relationship fields needed to be configured with the database field name. This made it confusing to set auth rules since often the user does not know what the database column name is (it usually maps to `{fieldName}Id`, but this knowledge is not apparent from the schema and is hard to track.
This fixes that so it can be configured with the model field name instead.
This PR also updates the docs, which showed configuration happening from the 1:M side, whereas it should be from the M:1 side.
Before and after:
```patch
Comment: {
relations: {
-    noteId: {
+    note: {
roles: ['admin']
}
}
}
```
> fix(keycloak-authz): make relationship field auth configurable at GraphQL field level

- packages/graphback-datasync/src/util.ts
The `ConflictError` message always gives an error message of `""`
> fix(datasync): add conflict error message

- docs/datasync/delta-queries.md
- docs/datasync/intro.md
- docs/releases.md
- packages/graphback-datasync/src/helpers/createDataSync.ts
- templates/ts-apollo-mongodb-datasync-backend/src/index.ts
This PR updates the docs with information on how to use the DataSync plugin without `createDataSyncAPI`.
It also adds an interface for the `createDataSyncAPI` config.
> docs: add DataSync plugin usage guide

- docs/releases.md
- packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
- packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreatorTest.ts.snap
Fixes #2113 
The `SchemCRUDPlugin` was still checking both `sub{Create,Update,Delete}` and `{create,update,delete}` were true before creating subscription fields
> fix(codegen-schema): create subscription fields when mutations are disabled

- templates/ts-apollo-mongodb-backend/tsconfig.json
- templates/ts-apollo-mongodb-datasync-backend/tsconfig.json
- templates/ts-apollo-postgres-backend/tsconfig.json
Running `yarn build` failed on fullstack templates as the `tsconfig.json` is not configured to compile React and does not have the required dependencies.
Since the client template comes with react-scripts, we can let them be built individually.
> chore(templates): exclude directories from build

- packages/graphback-datasync/src/DataSyncPlugin.ts
- packages/graphback-datasync/tests/DataSyncPluginTest.ts
- packages/graphql-serve/src/commands/printSchema.ts
Fixes https://github.com/aerogear/graphback/issues/2117
The DataSyncPlugin was creating empty root Query, Mutation and Subscription resolver objects.
> remove empty resolver creation in plugin

- packages/graphback-codegen-client/src/templates/gqlTemplates.ts
- packages/graphback-codegen-client/tests/__snapshots__/GraphQLClientCreatorTest.ts.snap
I think I have found a fix for issue #1965. The indentation issue would have also come when using subscriptions so I've tried to fix that too. 
I could not test my changes. I followed the written instructions but had the following problem:
1. First I changed the path of extensions.graphback.model in the .graphqlrc file,
2. Then I ran the command in the templates folder and received this error,
While I wasn't able to test it I think the changes I've made should fix the issue.
> fix: remove indent from generated query

- package.json
Fix to Issue #2150
Dev dependency on jest was missing so users are unable to run tests on fresh clones without installing jest manually.
> fix: add jest to dev dependencies

- packages/graphback-codegen-client/src/templates/gqlTemplates.ts
- packages/graphback-codegen-client/src/templates/tsTemplates.ts
- packages/graphback-codegen-client/tests/GraphQLClientCreatorTest.ts
- packages/graphback-codegen-client/tests/__snapshots__/GraphQLClientCreatorTest.ts.snap
I've updated the ```if``` conditions and it now depends only on the ```subXXX``` knobs. This should fix issue #2135. Please review the code. Thanks.
> fix: unable to generate subscription query unless mutation operation in model is set to `true`

- tsconfig.json
This generates a corresponding `.d.ts.map` file for each declaration file. It means that when someone uses "go to definition" on anything imported from a graphback package they will end up at the original definition in `src/foo.ts` rather than in a type definition file `types/foo.d.ts`
> Enable TypeScript declaration maps

- templates/ts-apollo-postgres-backend/docker-compose.yml
Issue link : [ISSUE-1195](https://github.com/tighten/takeout/issues/1195)
The following contains information on how I tested if database migrations work with v11 of PostgreSQL docker
1.  Created a Graphback application/project and chose postgres template
2.  Modified postgres template's docker-compose.yml to use postgres image of version 11.9
- 11.9 is the stable 11.x version of postgres image
- Click [here](https://hub.docker.com/_/postgres) for Dockerhub reference
3. Booted up the postgres docker container 
4. Connected with the postgres docker container and checked if the default users database is set up as configured in docker-compose.yml.
- **Note : As you can see in the image, the users database has no relations/tables**
5. Started the application server
6. Checked if migrations are …
> [ISSUE-1195]: Updated Docker PostgreSQL templates to use stable postgres docker image of version 11.9

- packages/graphback-datasync/src/DataSyncPlugin.ts
- packages/graphback-datasync/tests/__snapshots__/DataSyncPlugin.test.ts.snap
- packages/graphback-datasync/tests/mock.graphql
It is not possible to simply answer relationships status for single model - relationships are build per entire schema which will make it hard to use this info in data sync that typically works with subset of types.
Creating to see how we can get that done for the demo and fix datasync.
See #2163
> fix: adding relationships to datasync plugin

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreator.test.ts.snap
- packages/graphback-codegen-schema/tests/mock.graphql
- templates/ts-apollo-mongodb-backend/model/datamodel.graphql
Fixes https://github.com/aerogear/graphback/issues/2203
Given model:
```graphql
"""@model"""
type ModelWithArrayScalar {
id: ID!
roles: [String!]!
}
```
This will create the input type:
```graphql
input MutateModelWithArrayScalar {
id: ID!
roles: [String]
}
```
> fix(codegen-schema): map String list to String list in input type

- packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
- packages/graphql-serve/src/GraphbackServer.ts
Fix for failing checks in PR #2167 
These are the errors due to which the checks are failing for PR #2167:
* Property 'deprecationReason' is missing in type '{ name: string; type: GraphQLInputType; description: undefined; extensions: undefined[]; }' but required in type 'GraphQLInputField'.
* Property 'deprecationReason' is missing in type '{ name: string; type: GraphQLNonNull<GraphQLNullableType>; description: undefined; extensions: undefined; }' but required in type 'GraphQLInputField'.
* Type '{ name: string; type: any; extensions: any[]; }[]' is not assignable to type 'GraphQLInputField[]'.
I have added the necessary fixes which once merged, will ensure that all the checks for the PR #2167 are passed.
> fix(deps): fix for failing dependency bumps

- templates/ts-react-apollo-client/src/App.tsx
- templates/ts-react-apollo-client/src/components/notes/OneNote.tsx
While running the react template I noticed two minor warnings. While they don't affect the worrking in any way I though it'd be good to fix them anyways. 
Before:
After:
1. The first one was due to unused import of two material ui components which I've removed.
2. The second one was due to nothing being returned if a comment wasn't found. I've returned `null` here instead. But I think the entire `if` statement might be unnecessary since we do check if the comments array is present and has length greated than zero. 
Please let me know if you've some other suggestions. Thanks!
> chore(react-client-template): Fixes for minor warnings shown

- packages/create-graphback/src/init/starterTemplates.ts
The following error causes the create-graphback package to break:
```python
TypeError: request_1.default is not a function
at /home/namit/.npm/_npx/110767/lib/node_modules/create-graphback/dist/init/starterTemplates.js:140:30
at new Promise (<anonymous>)
at /home/namit/.npm/_npx/110767/lib/node_modules/create-graphback/dist/init/starterTemplates.js:139:15
at Generator.next (<anonymous>)
at /home/namit/.npm/_npx/110767/lib/node_modules/create-graphback/node_modules/tslib/tslib.js:115:75
at new Promise (<anonymous>)
at Object.__awaiter (/home/namit/.npm/_npx/110767/lib/node_modules/create-graphback/node_modules/tslib/tslib.js:111:16)
at downloadRepository (/home/namit/.npm/_npx/110767/lib/node_modules/create-graphback/dist/init/starterTemplates.js:133:20)
at Object.<anonymous> …
```
> fix(create-graphback): update import format

- packages/create-graphback/src/init/starterTemplates.ts
- templates/ts-apollo-postgres-backend/model/datamodel.graphql
- templates/ts-apollo-postgres-backend/src/generated-types.ts
- templates/ts-apollo-postgres-backend/src/schema/schema.graphql
- templates/ts-react-apollo-client/schema.graphql
- templates/ts-react-apollo-client/src/App.tsx
- templates/ts-react-apollo-client/src/components/comment/OneComment.tsx
- templates/ts-react-apollo-client/src/components/notes/EditNote.tsx
- templates/ts-react-apollo-client/src/components/notes/OneNote.tsx
- templates/ts-react-apollo-client/src/generated-types.tsx
- templates/ts-react-apollo-client/src/graphql/graphback.graphql
Fixes #2249 
I tried running the CLI locally after the change and it was working. To test that the client and Postgres templates are working as well I copied them from the project directory and ran them individually and they are working as shown in the video.
https://user-images.githubusercontent.com/56963264/107873710-5866f380-6eda-11eb-9365-5255a9636469.mp4
After discussion, it was decided to have the client app working with Postgres only and not mongo since client side queries are still there for testing if needed. To make the client template work with Postgres I made the following two changes:
1.  Replaced `_id` with `id` in postgres template's [datamodel.graphql](https://github.com/aerogear/graphback/blob/master/templates/ts …
> fix(templates): replaced _id with id in client and postgres template
